# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.api.generative_model_testing_api import GenerativeModelTestingApi


class TestGenerativeModelTestingApi(unittest.TestCase):
    """GenerativeModelTestingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenerativeModelTestingApi()

    def tearDown(self) -> None:
        pass

    def test_quick_scan(self) -> None:
        """Test case for quick_scan

        QuickScan
        """
        pass

    def test_results(self) -> None:
        """Test case for results

        GetGenerativeModelTestResults
        """
        pass

    def test_start_generative_test(self) -> None:
        """Test case for start_generative_test

        StartGenerativeModelTest
        """
        pass


if __name__ == '__main__':
    unittest.main()