# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.statedb_job_status import StatedbJobStatus

class TestStatedbJobStatus(unittest.TestCase):
    """StatedbJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatedbJobStatus(self):
        """Test StatedbJobStatus"""
        # inst = StatedbJobStatus()

if __name__ == '__main__':
    unittest.main()