# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.generativetesting_start_generative_model_test_request import GenerativetestingStartGenerativeModelTestRequest

class TestGenerativetestingStartGenerativeModelTestRequest(unittest.TestCase):
    """GenerativetestingStartGenerativeModelTestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerativetestingStartGenerativeModelTestRequest:
        """Test GenerativetestingStartGenerativeModelTestRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerativetestingStartGenerativeModelTestRequest`
        """
        model = GenerativetestingStartGenerativeModelTestRequest()
        if include_optional:
            return GenerativetestingStartGenerativeModelTestRequest(
                url = '',
                http_headers = {
                    'key' : ''
                    },
                endpoint_payload_template = '',
                response_json_path = '',
                http_auth_integration_id = ri.apiclient.models.rime_uuid.rimeUUID(
                    uuid = '', ),
                name = '',
                mutual_tls_integration_id = ri.apiclient.models.rime_uuid.rimeUUID(
                    uuid = '', ),
                system_prompt = ''
            )
        else:
            return GenerativetestingStartGenerativeModelTestRequest(
                url = '',
                endpoint_payload_template = '',
                response_json_path = '',
        )
        """

    def testGenerativetestingStartGenerativeModelTestRequest(self):
        """Test GenerativetestingStartGenerativeModelTestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()