US_UULE = [
    "Alaska,United States",
    "Alabama,United States",
    "Arkansas,United States",
    "Arizona,United States",
    "California,United States",
    "Colorado,United States",
    "Connecticut,United States",
    "District of Columbia,United States",
    "Delaware,United States",
    "Florida,United States",
    "Georgia,United States",
    "Hawaii,United States",
    "Iowa,United States",
    "Idaho,United States",
    "Illinois,United States",
    "Indiana,United States",
    "Kansas,United States",
    "Kentucky,United States",
    "Louisiana,United States",
    "Massachusetts,United States",
    "Maryland,United States",
    "Maine,United States",
    "Michigan,United States",
    "Minnesota,United States",
    "Missouri,United States",
    "Mississippi,United States",
    "Montana,United States",
    "North Carolina,United States",
    "North Dakota,United States",
    "Nebraska,United States",
    "New Hampshire,United States",
    "New Jersey,United States",
    "New Mexico,United States",
    "Nevada,United States",
    "New York,United States",
    "Ohio,United States",
    "Oklahoma,United States",
    "Oregon,United States",
    "Pennsylvania,United States",
    "Rhode Island,United States",
    "South Carolina,United States",
    "South Dakota,United States",
    "Tennessee,United States",
    "Texas,United States",
    "Utah,United States",
    "Virginia,United States",
    "Vermont,United States",
    "Washington,United States",
    "Wisconsin,United States",
    "West Virginia,United States",
    "Wyoming,United States",
    "United States",
]
