# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:\software-dev\autologbook-dev\autologbook\ui\restore_element_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecoverElementDialog(object):
    def setupUi(self, RecoverElementDialog):
        RecoverElementDialog.setObjectName("RecoverElementDialog")
        RecoverElementDialog.resize(411, 372)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RecoverElementDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RecoverElementDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(RecoverElementDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.sample_selector = QtWidgets.QComboBox(RecoverElementDialog)
        self.sample_selector.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.sample_selector.setObjectName("sample_selector")
        self.gridLayout.addWidget(self.sample_selector, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(RecoverElementDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.filter_line_edit = QtWidgets.QLineEdit(RecoverElementDialog)
        self.filter_line_edit.setClearButtonEnabled(True)
        self.filter_line_edit.setObjectName("filter_line_edit")
        self.gridLayout.addWidget(self.filter_line_edit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_3 = QtWidgets.QLabel(RecoverElementDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.file_list_view = QtWidgets.QTableView(RecoverElementDialog)
        self.file_list_view.setAlternatingRowColors(True)
        self.file_list_view.setObjectName("file_list_view")
        self.file_list_view.horizontalHeader().setSortIndicatorShown(True)
        self.file_list_view.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.file_list_view)
        self.buttonBox = QtWidgets.QDialogButtonBox(RecoverElementDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_2.setBuddy(self.sample_selector)
        self.label_4.setBuddy(self.filter_line_edit)
        self.label_3.setBuddy(self.file_list_view)

        self.retranslateUi(RecoverElementDialog)
        self.buttonBox.accepted.connect(RecoverElementDialog.accept)
        self.buttonBox.rejected.connect(RecoverElementDialog.reject)
        self.sample_selector.currentIndexChanged['QString'].connect(RecoverElementDialog.sample_selector_changed)
        QtCore.QMetaObject.connectSlotsByName(RecoverElementDialog)

    def retranslateUi(self, RecoverElementDialog):
        _translate = QtCore.QCoreApplication.translate
        RecoverElementDialog.setWindowTitle(_translate("RecoverElementDialog", "Restore element from recycling bin"))
        self.label.setText(_translate("RecoverElementDialog", "From this dialog, it is possible to restore recycle elements that were stored in dedicated trash can. Each sample / subsample has its own trash can that can be selected via the sample combobox. From the list view, select the element(s) to be restore from the list below. "))
        self.label_2.setText(_translate("RecoverElementDialog", "Sample trash bin"))
        self.label_4.setText(_translate("RecoverElementDialog", "Quick filter"))
        self.label_3.setText(_translate("RecoverElementDialog", "Element in the trash bin"))
