categories = {
    'Attractions':        ['Amusement / Theme Park',
                           'Arena / Track',
                           'Hall / Auditorium',
                           'Landmark',
                           'Museum / Historical',
                           'Park / Garden',
                           'Winery'],
    'Auto Services':      ['Auto Club',
                           'Auto Rental',
                           'Auto Repair',
                           'Car Wash',
                           'Dealer / Auto Parts',
                           'Parking',
                           'Rest Area / Tourist Info',
                           'Truck Stop'],
    'Bank /ATM':          None,
    'Community':          ['Border Crossing ',
                           'City Hall',
                           'Community Centre',
                           'Court House',
                           'Fire Department',
                           'Government Office',
                           'Library',
                           'Place of Worship',
                           'Police Station',
                           'Post Office',
                           'School',
                           'Utility'],
    'Entertainment':      ['Bar / Nightclub',
                           'Casino',
                           'Hall / Auditorium',
                           'Live Theater',
                           'Movie Theater'],
    'Food & drink':       ['American',
                           'Asian',
                           'Bagel or Donut',
                           'Barbecue',
                           'British Isles',
                           'Café or diner',
                           'Chinese',
                           'Deli / Bakery',
                           'Fast Food',
                           'French ',
                           'German',
                           'International',
                           'Italian',
                           'Mexican',
                           'Other',
                           'Pizza',
                           'Seafood',
                           'Specialty Food Products',
                           'Steak / Grill'],
    'Fuel':               ['Auto Fuel',
                           'Convenience',
                           'Truck Stop'],
    'Geographic Places':  ['Land',
                           'Man Made',
                           'Water'],
    'Hospital':           None,
    'Lodging':            ['Bed and Breakfast Inn',
                           'Campground / RV Park',
                           'Hotel / Motel',
                           'Park',
                           'Sporting & Instructional Camp'],
    'Marine':             ['Chart Point',
                           'Current Station',
                           'Depth',
                           'Fishing',
                           'Marine Services',
                           'Navigation Aid',
                           'Obstruction / Danger',
                           'Other',
                           'Photo Point',
                           'Tide Station'],
    'Public Land Survey': ['Quad',
                           'Section',
                           'Township / Range'],
    'Other':              ['Business Service',
                           'Communications',
                           'GARMIN Dealer',
                           'Marina / Repair & Storage',
                           'Other',
                           'Personal Service',
                           'Repair Service',
                           'Social Service'],
    'Recreation':         ['Amusement / Theme Park',
                           'Arena / Track',
                           'Bowling Center',
                           'Golf Course',
                           'Park / Garden',
                           'Public Sports Airport',
                           'Skiing Center / Resort',
                           'Sports / Fitness Center'],
    'Shopping':           ['Apparel',
                           'Computer / Software',
                           'Convenience',
                           'Department',
                           'General Merchandise',
                           'Grocery',
                           'Home Furnishings',
                           'House & Garden',
                           'Pharmacy / Chemist',
                           'Shopping Center',
                           'Specialty Retail'],
    'Transportation':     ['Air Transportation',
                           'Auto Rental',
                           'Ground Transportation',
                           'Transit Service'],
}
