'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.20

version: 0.1.20

full_version: 0.1.20

git_revision: 4caad7e4df0467d90afdb3f12e9de61d276e1bdc

release: True

'''
short_version: str = '0.1.20'
version: str = '0.1.20'
full_version: str = '0.1.20'
git_revision: str = '4caad7e4df0467d90afdb3f12e9de61d276e1bdc'
release: bool = True
if not release:
    version = full_version
