# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/ConnectionMonitor/ConnectionMonitorServices.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openobd_protocol.ConnectionMonitor import ConnectionInformation_pb2 as openobd__protocol_dot_ConnectionMonitor_dot_ConnectionInformation__pb2
from openobd_protocol import BasicResponse_pb2 as openobd__protocol_dot_BasicResponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBopenobd_protocol/ConnectionMonitor/ConnectionMonitorServices.proto\x12/com.jifeline.OpenOBD.Protocol.ConnectionMonitor\x1a>openobd_protocol/ConnectionMonitor/ConnectionInformation.proto\x1a$openobd_protocol/BasicResponse.proto2\xc4\x02\n\x19\x43onnectionMonitorServices\x12\x8f\x01\n\x17getConnectorInformation\x12+.com.jifeline.OpenOBD.Protocol.EmptyMessage\x1a\x45.com.jifeline.OpenOBD.Protocol.ConnectionMonitor.ConnectorInformation\"\x00\x12\x94\x01\n\x1astreamConnectorInformation\x12+.com.jifeline.OpenOBD.Protocol.EmptyMessage\x1a\x45.com.jifeline.OpenOBD.Protocol.ConnectionMonitor.ConnectorInformation\"\x00\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.ConnectionMonitor.ConnectionMonitorServices_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CONNECTIONMONITORSERVICES']._serialized_start=222
  _globals['_CONNECTIONMONITORSERVICES']._serialized_end=546
# @@protoc_insertion_point(module_scope)
