from setuptools import setup, find_packages

setup(
    name='my_chatbot_lib',
    version='0.1.0',
    description='A chatbot library',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/Evasas12/Chabot',
    author='BSCS 4-5',
    author_email='chuasweet11@gmail.com',
    license='MIT',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    keywords='chatbot library NLP',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Flask',
        'experta',
        'nltk',
        'scikit-learn',
        'pymongo',
    ],
    python_requires='>=3.6',
)