
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-12T09:46:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b330ea5bb90a86e75980c420ca47c2b95088059",
 "version": "1.26.0.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
