# coding: utf-8
"""
    Superwise Main Entities

    API reference

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel
from pydantic import Field
from pydantic import StrictStr


class AskResponsePayload(BaseModel):
    """
    AskResponsePayload
    """

    output: StrictStr = Field(..., description="The AI agent's response to the user's inquiry.")
    __properties = ["output"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AskResponsePayload:
        """Create an instance of AskResponsePayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AskResponsePayload:
        """Create an instance of AskResponsePayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AskResponsePayload.parse_obj(obj)

        _obj = AskResponsePayload.parse_obj({"output": obj.get("output")})
        return _obj
