track_navi_data = {
    "GOLD RUSH": {
        "trackcn": "淘金狂飙",
        "2": [{"key": "Y", "down": 63}, {"key": "Y", "down": 124}],
        "14": [{"key": "DPAD_LEFT", "down": 85}],
        "15": [{"key": "DPAD_LEFT", "down": 85}],
        "17": [{"key": "Y", "down": 113}, {"key": "Y", "down": 84}],
        "28": [{"key": "B", "down": 8582}],
        "42": [{"key": "Y", "down": 133}, {"key": "Y", "down": 106}],
        "44": [{"key": "B", "down": 1453}],
        "47": [{"key": "DPAD_LEFT", "down": 130}],
        "48": [{"key": "DPAD_LEFT", "down": 130}],
        "50": [{"key": "Y", "down": 128}, {"key": "Y", "down": 84}],
        "65": [{"key": "DPAD_RIGHT", "down": 103}],
        "66": [{"key": "DPAD_RIGHT", "down": 103}],
        "69": [{"key": "Y", "down": 132}, {"key": "Y", "down": 87}],
        "76": [{"key": "DPAD_LEFT", "down": 75}],
        "77": [{"key": "DPAD_LEFT", "down": 75}],
        "88": [{"key": "B", "down": 2933}],
        "93": [{"key": "Y", "down": 123}, {"key": "Y", "down": 101}],
    },
    "ANCIENT RUINS": {
        "trackcn": "古代遗迹",
        "1": [{"key": "DPAD_RIGHT", "down": 109}],
        "2": [{"key": "DPAD_RIGHT", "down": 109}],
        "4": [{"key": "DPAD_RIGHT", "down": 107}],
        "5": [{"key": "DPAD_RIGHT", "down": 107}],
        "8": [{"key": "Y", "down": 47}, {"key": "Y", "down": 116}],
        "15": [{"key": "DPAD_RIGHT", "down": 100}],
        "16": [{"key": "DPAD_RIGHT", "down": 100}],
        "27": [{"key": "Y", "down": 78}, {"key": "Y", "down": 104}],
        "29": [
            {"key": "DPAD_RIGHT", "down": 204},
            {"key": "Y", "down": 78},
            {"key": "Y", "down": 104},
        ],
        "30": [{"key": "DPAD_RIGHT", "down": 204}],
        "33": [{"key": "DPAD_LEFT", "down": 178}],
        "34": [{"key": "DPAD_LEFT", "down": 178}],
        "38": [{"key": "DPAD_LEFT", "down": 94}],
        "39": [{"key": "DPAD_LEFT", "down": 94}],
        "41": [{"key": "Y", "down": 118}, {"key": "Y", "down": 102}],
        "51": [{"key": "B", "down": 10093}],
        "65": [{"key": "Y", "down": 150}, {"key": "Y", "down": 126}],
        "67": [{"key": "DPAD_LEFT", "down": 196}],
        "68": [{"key": "DPAD_LEFT", "down": 196}],
        "69": [{"key": "B", "down": 2116}],
        "74": [{"key": "Y", "down": 133}, {"key": "Y", "down": 108}],
        "77": [{"key": "B", "down": 1545}],
        "80": [{"key": "Y", "down": 137}, {"key": "Y", "down": 111}],
        "83": [{"key": "B", "down": 1814}],
        "87": [{"key": "Y", "down": 151}, {"key": "Y", "down": 96}],
        "89": [{"key": "DPAD_LEFT", "down": 150}],
        "90": [{"key": "DPAD_LEFT", "down": 150}],
        "92": [{"key": "B", "down": 2148}],
        "96": [{"key": "Y", "down": 129}, {"key": "Y", "down": 109}],

    },
    "NANJING STROLL": {
        "trackcn": "漫步南京路",
        "0": [{"key": "DPAD_RIGHT", "down": 76}, {"key": "DPAD_RIGHT", "down": 76}],
        "1": [{"key": "Y", "down": 112}, {"key": "Y", "down": 75}],
        "22": [{"key": "Y", "down": 80}, {"key": "Y", "down": 75}],
        "29": [{"key": "B", "down": 1831}],
        "34": [{"key": "Y", "down": 138}, {"key": "Y", "down": 100}],
        "37": [{"key": "B", "down": 11499}],
        "54": [{"key": "Y", "down": 118}, {"key": "Y", "down": 86}],
        "56": [{"key": "B", "down": 3389}],
        "60": [{"key": "Y", "down": 108}, {"key": "Y", "down": 90}],
        "66": [{"key": "B", "down": 2522}],
        "70": [
            {"key": "DPAD_LEFT", "down": 185},
            {"key": "DPAD_LEFT", "down": 185},
        ],
        "72": [{"key": "Y", "down": 102}, {"key": "Y", "down": 82}],
        "74": [{"key": "B", "down": 2690}],
        "78": [{"key": "Y", "down": 114}, {"key": "Y", "down": 88}],
        "82": [{"key": "B", "down": 3026}],
        "87": [{"key": "Y", "down": 134}, {"key": "Y", "down": 87}],
        "89": [{"key": "B", "down": 1406}],
        "91": [{"key": "Y", "down": 138}, {"key": "Y", "down": 98}],
        "93": [{"key": "B", "down": 1364}],
        "96": [{"key": "Y", "down": 102}, {"key": "Y", "down": 87}], 
    },
}
