track_data = [
    {
        "key": "NEVADA_Long_Run_120",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "1",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "LONG RUN",
        "trackcn": "长路慢慢",
        "time": "120",
    },
    {
        "key": "NEVADA_The_Curve_120",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "1",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "THE CURVE",
        "trackcn": "弯道争霸",
        "time": "120",
    },
    {
        "key": "San_Francisco_City_Dash_60",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "1",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "CITY DASH",
        "trackcn": "城市狂飙",
        "time": "60",
    },
    {
        "key": "San_Francisco_Waterside_60",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "2",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "WATERSIDE",
        "trackcn": "水滨",
        "time": "60",
    },
    {
        "key": "Himalayas_Freefall_30",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "3",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "FREEFALL",
        "trackcn": "自由落体",
        "time": "30",
    },
    {
        "key": "Himalayas_Snow_Vault_60",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "4",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "SNOW VAULT",
        "trackcn": "冰雪地堡",
        "time": "60",
    },
    {
        "key": "Himalayas_Landslide_60",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "5",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "LANDSLIDE",
        "trackcn": "山崩",
        "time": "60",
    },
    {
        "key": "San_Francisco_The_City_by_the_Bay_90",
        "chapter": "1",
        "season": "Legendary Start",
        "race": "6",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "THE CITY BY THE BAY",
        "trackcn": "临湾城市",
        "time": "90",
    },
    {
        "key": "Scotland_The_Enchanted_Island_60",
        "chapter": "1",
        "season": "Gearheads",
        "race": "1",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "THE ENCHANTED ISLAND",
        "trackcn": "魔法岛屿",
        "time": "60",
    },
    {
        "key": "Scotland_Ghost_Ships_30",
        "chapter": "1",
        "season": "Gearheads",
        "race": "2",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "GHOST SHIPS",
        "trackcn": "幽灵船",
        "time": "30",
    },
    {
        "key": "Scotland_Ancient_Ruins_90",
        "chapter": "1",
        "season": "Gearheads",
        "race": "3",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "ANCIENT RUINS",
        "trackcn": "古代遗迹",
        "time": "90",
    },
    {
        "key": "San_Francisco_The_Tunnel_30",
        "chapter": "1",
        "season": "Gearheads",
        "race": "4",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "THE TUNNEL",
        "trackcn": "隧道",
        "time": "30",
    },
    {
        "key": "San_Francisco_Downtown_Rise_90",
        "chapter": "1",
        "season": "Gearheads",
        "race": "5",
        "modeen": "Time Attack",
        "locationen": "SAN FRANCISCO",
        "tracken": "DOWNTOWN RISE",
        "trackcn": "市中心高架桥",
        "time": "90",
    },
    {
        "key": "San_Francisco_Roller_Coaster_Ride_90",
        "chapter": "1",
        "season": "Gearheads",
        "race": "6",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "ROLLER",
        "trackcn": "云霄飞车",
        "time": "90",
    },
    {
        "key": "Scotland_Lighthouse_60",
        "chapter": "1",
        "season": "Gearheads",
        "race": "7",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "LIGHTHOUSE",
        "trackcn": "灯塔",
        "time": "60",
    },
    {
        "key": "Scotland_Rocky_Valley_30",
        "chapter": "1",
        "season": "Gearheads",
        "race": "8",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "ROCKY VALLEY",
        "trackcn": "岩石山谷",
        "time": "30",
    },
    {
        "key": "Scotland_The_Path_of_the_Wind_90",
        "chapter": "1",
        "season": "Gearheads",
        "race": "9",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "THE PATH OF THE WIND",
        "trackcn": "风之小径",
        "time": "90",
    },
    {
        "key": "Scotland_The_Windmills_120",
        "chapter": "1",
        "season": "Gearheads",
        "race": "10",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "THE WINDMILLS",
        "trackcn": "风车",
        "time": "120",
    },
    {
        "key": "Himalayas_Cliffhanger_90",
        "chapter": "1",
        "season": "Class D Novice",
        "race": "2",
        "modeen": "Time Attack",
        "locationen": "HIMALAYAS",
        "tracken": "CLIFFHANGER",
        "trackcn": "悬崖峭壁",
        "time": "90",
    },
    {
        "key": "Shanghai_Reach_for_the_Sky_60",
        "chapter": "1",
        "season": "Class D Novice",
        "race": "3",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "REACH FOR THE SKY",
        "trackcn": "触摸天空",
        "time": "60",
    },
    {
        "key": "Himalayas_Dipping_Down_90",
        "chapter": "1",
        "season": "Class D Novice",
        "race": "8",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "DIPPING DOWN",
        "trackcn": "坠落",
        "time": "90",
    },
    {
        "key": "Himalayas_The_Land_of_Snow_120",
        "chapter": "1",
        "season": "Class D Novice",
        "race": "10",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "THE LAND OF SNOW",
        "trackcn": "冰雪大地",
        "time": "120",
    },
    {
        "key": "Shanghai_Future_Road_60",
        "chapter": "1",
        "season": "BMW Z4",
        "race": "1",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "FUTURE ROAD",
        "trackcn": "未来之路",
        "time": "60",
    },
    {
        "key": "Shanghai_Double_Roundabout_30",
        "chapter": "1",
        "season": "BMW Z4",
        "race": "4",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "DOUBLE ROUNDABOUT",
        "trackcn": "双环岛",
        "time": "30",
    },
    {
        "key": "Shanghai_Paris_of_the_East_30",
        "chapter": "1",
        "season": "BMW Z4",
        "race": "6",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "PARIS OF THE EAST",
        "trackcn": "东方巴黎",
        "time": "30",
    },
    {
        "key": "Shanghai_Pudong_Rise_90",
        "chapter": "1",
        "season": "BMW Z4",
        "race": "8",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "PUDONG RISE",
        "trackcn": "浦东崛起",
        "time": "90",
    },
    {
        "key": "Shanghai_The_Pearl_of_the_Orient_90",
        "chapter": "1",
        "season": "Class C Novice",
        "race": "4",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "THE PEARL OF THE ORIENT",
        "trackcn": "东方明珠",
        "time": "90",
    },
    {
        "key": "Himalayas_Frozen_Route_90",
        "chapter": "1",
        "season": "Class C Novice",
        "race": "11",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "FROZEN ROUTE",
        "trackcn": "冰封路径",
        "time": "90",
    },
    {
        "key": "Himalayas_Leap_of_Faith_30",
        "chapter": "1",
        "season": "Exclusive Challenge Asia",
        "race": "2",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "LEAP OF FAITH",
        "trackcn": "信仰之跃",
        "time": "30",
    },
    {
        "key": "Shanghai_Nanjing_Stroll_90",
        "chapter": "1",
        "season": "Exclusive Challenge Asia",
        "race": "4",
        "modeen": "Time Attack",
        "locationen": "SHANGHAI",
        "tracken": "NANJING STROLL",
        "trackcn": "漫步南京路",
        "time": "90",
    },
    {
        "key": "Himalayas_Mountain_Poles_90",
        "chapter": "1",
        "season": "Exclusive Challenge Asia",
        "race": "5",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "MOUNTAIN POLES",
        "trackcn": "山巅",
        "time": "90",
    },
    {
        "key": "Shanghai_Shopping_Spree_120",
        "chapter": "1",
        "season": "Exclusive Challenge Asia",
        "race": "10",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "SHOPPING SPREE",
        "trackcn": "购物狂欢",
        "time": "120",
    },
    {
        "key": "San_Francisco_Final_del_Puente_120",
        "chapter": "1",
        "season": "Escape",
        "race": "2",
        "modeen": "Hunted",
        "locationen": "SAN FRANCISCO",
        "tracken": "FINAL DEL PUENTE",
        "trackcn": "大桥之战",
        "time": "120",
    },
    {
        "key": "US_Midwest_US_Wilderness_120",
        "chapter": "1",
        "season": "Escape",
        "race": "3",
        "modeen": "Hunted",
        "locationen": "US MIDWEST",
        "tracken": "US WILDERNESS",
        "trackcn": "美国荒野",
        "time": "120",
    },
    {
        "key": "Rome_Tiber_Cross_60",
        "chapter": "1",
        "season": "Escape",
        "race": "4",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "TIBER CROSS",
        "trackcn": "穿越台伯河",
        "time": "60",
    },
    {
        "key": "Rome_Complete_Tour_120",
        "chapter": "1",
        "season": "Escape",
        "race": "5",
        "modeen": "Hunted",
        "locationen": "ROME",
        "tracken": "COMPLETE TOUR",
        "trackcn": "完成巡回赛",
        "time": "120",
    },
    {
        "key": "Scotland_Freedom_Route_120",
        "chapter": "1",
        "season": "Escape",
        "race": "6",
        "modeen": "Hunted",
        "locationen": "SCOTLAND",
        "tracken": "FREEDOM ROUTE",
        "trackcn": "自由路线",
        "time": "120",
    },
    {
        "key": "San_Francisco_Railroad_Bustle_30",
        "chapter": "1",
        "season": "Camaro",
        "race": "1",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "RAILROAD BUSTLE",
        "trackcn": "喧闹铁路",
        "time": "30",
    },
    {
        "key": "Scotland_The_Cave_90",
        "chapter": "1",
        "season": "Camaro",
        "race": "9",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "THE CAVE",
        "trackcn": "洞穴",
        "time": "90",
    },
    {
        "key": "San_Francisco_Streets_of_San_Francisco_90",
        "chapter": "1",
        "season": "Camaro",
        "race": "10",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "STREETS OF SAN",
        "trackcn": "旧金山街道",
        "time": "90",
    },
    {
        "key": "Cairo_Urban_Blaze_90",
        "chapter": "1",
        "season": "Class D Rookie",
        "race": "1",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "URBAN BLAZE",
        "trackcn": "城市烈焰",
        "time": "90",
    },
    {
        "key": "Cairo_A_Kings_Revival_30",
        "chapter": "1",
        "season": "Class D Rookie",
        "race": "4",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "A KINGS REVIVAL",
        "trackcn": "国王的复兴",
        "time": "30",
    },
    {
        "key": "Cairo_Subterranean_Dash_60",
        "chapter": "1",
        "season": "Class D Rookie",
        "race": "5",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "SUBTERRANEAN DASH",
        "trackcn": "地下冲刺",
        "time": "60",
    },
    {
        "key": "Cairo_Scenic_Route_120",
        "chapter": "1",
        "season": "Class D Rookie",
        "race": "10",
        "modeen": "Hunted",
        "locationen": "CAIRO",
        "tracken": "SCENIC ROUTE",
        "trackcn": "观光路线",
        "time": "120",
    },
    {
        "key": "Cairo_Cairo_Tower_Finish_60",
        "chapter": "1",
        "season": "Class D Rookie",
        "race": "11",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "CAIRO TOWER FINISH",
        "trackcn": "开罗塔终点",
        "time": "60",
    },
    {
        "key": "Osaka_Meiji_Rush_30",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "1",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "MEIJI RUSH",
        "trackcn": "明治冲击",
        "time": "30",
    },
    {
        "key": "Osaka_Budding_Start_90",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "2",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "BUDDING START",
        "trackcn": "崭露头角",
        "time": "90",
    },
    {
        "key": "Osaka_Sakura_Castle_60",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "3",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "SAKURA CASTLE",
        "trackcn": "樱花城堡",
        "time": "60",
    },
    {
        "key": "Osaka_Industrial_Revolution_90",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "4",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "INDUSTRIAL REVOLUTION",
        "trackcn": "工业革命",
        "time": "90",
    },
    {
        "key": "Osaka_Rat_Race_60",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "5",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "RAT RACE",
        "trackcn": "急速之争",
        "time": "60",
    },
    {
        "key": "Osaka_Naniwa_Tour_90",
        "chapter": "1",
        "season": "The Heart of Kansai",
        "race": "6",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "NANIWA TOUR",
        "trackcn": "逐浪之旅",
        "time": "90",
    },
    {
        "key": "Cairo_Gezira_Island_30",
        "chapter": "2",
        "season": "Class D Pro",
        "race": "1",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "GEZIRA ISLAND",
        "trackcn": "杰基拉岛",
        "time": "30",
    },
    {
        "key": "Cairo_Ancient_Wonders_90",
        "chapter": "2",
        "season": "Class D Pro",
        "race": "6",
        "modeen": "Time Attack",
        "locationen": "CAIRO",
        "tracken": "ANCIENT WONDER",
        "trackcn": "古老奇观",
        "time": "90",
    },
    {
        "key": "Cairo_Thousand_Minarets_90",
        "chapter": "2",
        "season": "Class D Pro",
        "race": "10",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "THOUSAND",
        "trackcn": "尖塔耸立",
        "time": "90",
    },
    {
        "key": "Shanghai_People_Square_Dash_120",
        "chapter": "2",
        "season": "Class D Pro",
        "race": "12",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "PEOPLE SQUARE DASH",
        "trackcn": "人民广场狂飙",
        "time": "120",
    },
    {
        "key": "US_Midwest_Its_a_Twister_30",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "1",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "ITS A TWISTER",
        "trackcn": "龙卷风",
        "time": "30",
    },
    {
        "key": "US_Midwest_Trainspotter_30",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "2",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "TRAINSPOTTER",
        "trackcn": "铁道迷",
        "time": "30",
    },
    {
        "key": "US_Midwest_Rolling_Motorway_60",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "3",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "ROLLING MOTORWAY",
        "trackcn": "曲直高速",
        "time": "60",
    },
    {
        "key": "US_Midwest_Transcontinental_Race_90",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "4",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "TRANSCONTINE RACE",
        "trackcn": "横贯大陆赛事",
        "time": "90",
    },
    {
        "key": "US_Midwest_Canyon_Launch_90",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "8",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "CANYON LAUNCH",
        "trackcn": "峡谷飞驰",
        "time": "90",
    },
    {
        "key": "US_Midwest_Whirlwind_Curve_90",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "9",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "WHIRLWIND",
        "trackcn": "旋风弯道",
        "time": "90",
    },
    {
        "key": "US_Midwest_Gold_Rush_90",
        "chapter": "2",
        "season": "Ultimate Muscle",
        "race": "12",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "GOLD RUSH",
        "trackcn": "淘金狂飙",
        "time": "90",
    },
    {
        "key": "Rome_The_Eternal_City_90",
        "chapter": "2",
        "season": "Class C Rookie",
        "race": "5",
        "modeen": "Time Attack",
        "locationen": "ROME",
        "tracken": "THE ETERNAL CITY",
        "trackcn": "永恒之城",
        "time": "90",
    },
    {
        "key": "Cairo_Pharaoh_Games_120",
        "chapter": "2",
        "season": "Class C Rookie",
        "race": "6",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "PHARAOH GAMES",
        "trackcn": "法老游戏",
        "time": "120",
    },
    {
        "key": "Rome_Bread_and_Circuses_60",
        "chapter": "2",
        "season": "Class C Rookie",
        "race": "9",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "BREAD AND CIRCUSES",
        "trackcn": "旧时风情",
        "time": "60",
    },
    {
        "key": "Shanghai_Shen_City_90",
        "chapter": "2",
        "season": "Class C Rookie",
        "race": "12",
        "modeen": "Classic",
        "locationen": "SHANGHAI",
        "tracken": "SHEN CITY",
        "trackcn": "申城",
        "time": "90",
    },
    {
        "key": "Rome_Capital_of_the_World_90",
        "chapter": "2",
        "season": "Class C Rookie",
        "race": "14",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "CAPITAL OF THE WORLD",
        "trackcn": "世界大都会",
        "time": "90",
    },
    {
        "key": "US_Midwest_Time_Travel_60",
        "chapter": "2",
        "season": "Green Machines",
        "race": "4",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "TIME TRAVEL",
        "trackcn": "时间旅行",
        "time": "60",
    },
    {
        "key": "US_Midwest_Navajo_Nation_120",
        "chapter": "2",
        "season": "Green Machines",
        "race": "14",
        "modeen": "Classic",
        "locationen": "US MIDWEST",
        "tracken": "NAVAJO NATION",
        "trackcn": "印第安国度",
        "time": "120",
    },
    {
        "key": "Rome_Saint_Peter_Kickoff_90",
        "chapter": "2",
        "season": "Class B Novice",
        "race": "3",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "SAINT PETER",
        "trackcn": "圣彼得狂飙",
        "time": "90",
    },
    {
        "key": "Scotland_Wildlands_90",
        "chapter": "2",
        "season": "Class B Novice",
        "race": "7",
        "modeen": "Classic",
        "locationen": "SCOTLAND",
        "tracken": "WILDLANDS",
        "trackcn": "荒地",
        "time": "90",
    },
    {
        "key": "Rome_Alternate_Route_120",
        "chapter": "2",
        "season": "Class D Elite",
        "race": "13",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "ALTERNATE ROUTE",
        "trackcn": "迂回路线",
        "time": "120",
    },
    {
        "key": "Nevada_Desert_Life_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "1",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "DESERT LIFE",
        "trackcn": "沙漠生命",
        "time": "90",
    },
    {
        "key": "New_York_Quantum_Jumps_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "2",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "QUANTUM JUMPS",
        "trackcn": "量子跃迁",
        "time": "90",
    },
    {
        "key": "Nevada_Dam_Buster_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "3",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "DAM BUSTER",
        "trackcn": "大坝克星",
        "time": "90",
    },
    {
        "key": "Nevada_The_Narrows_120",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "4",
        "modeen": "Hunted",
        "locationen": "NEVADA",
        "tracken": "THE NARROWS",
        "trackcn": "狭路争霸",
        "time": "120",
    },
    {
        "key": "Nevada_Bridge_to_Bridge_30",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "6",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "BRIDGE TO BRIDGE",
        "trackcn": "桥间争霸",
        "time": "30",
    },
    {
        "key": "Himalayas_Asphalt_Cave_120",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "7",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "ASPHALT CAVE",
        "trackcn": "狂飙洞穴",
        "time": "120",
    },
    {
        "key": "New_York_Leaps_&_Bounds_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "8",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "LEAPS & BOUNDS",
        "trackcn": "急速飞跃",
        "time": "90",
    },
    {
        "key": "Nevada_Desert_Run_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "9",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "DESERT RUN",
        "trackcn": "沙漠狂飙",
        "time": "90",
    },
    {
        "key": "Nevada_Desert_Drift_90",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "10",
        "modeen": "Time Attack",
        "locationen": "NEVADA",
        "tracken": "DESERT DRIFT",
        "trackcn": "沙漠漂移",
        "time": "90",
    },
    {
        "key": "Nevada_Sprint_Finish_120",
        "chapter": "2",
        "season": "Full Throttle Season",
        "race": "11",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "SPRINT FINISH",
        "trackcn": "终点冲刺",
        "time": "120",
    },
    {
        "key": "Rome_Roman_Byroads_30",
        "chapter": "2",
        "season": "Class C Pro",
        "race": "5",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "ROMAN BYROADS",
        "trackcn": "罗马小道",
        "time": "30",
    },
    {
        "key": "Rome_Roman_Tumble_30",
        "chapter": "2",
        "season": "Class C Pro",
        "race": "8",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "ROMAN TUMBLE",
        "trackcn": "跌宕罗马",
        "time": "30",
    },
    {
        "key": "New_York_Uptown_90",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "1",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "UPTOWN",
        "trackcn": "住宅区",
        "time": "90",
    },
    {
        "key": "New_York_The_City_that_Never_Sleeps_90",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "2",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "THE CITY THAT NEVER SLEEPS",
        "trackcn": "不夜城",
        "time": "90",
    },
    {
        "key": "New_York_Trainspotter_30",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "4",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "TRAINSPOTTER",
        "trackcn": "铁道迷",
        "time": "30",
    },
    {
        "key": "New_York_Airdropped_90",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "5",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "AIRDROPPED",
        "trackcn": "空投",
        "time": "90",
    },
    {
        "key": "New_York_Subway_Surfing_90",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "6",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "SUBWAY SURFING",
        "trackcn": "地铁冲浪",
        "time": "90",
    },
    {
        "key": "New_York_Sightseeing_120",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "7",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "SIGHTSEEING",
        "trackcn": "观光游览",
        "time": "120",
    },
    {
        "key": "New_York_A_Run_in_the_Park_30",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "8",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "A RUN IN THE PARK",
        "trackcn": "公园竞赛",
        "time": "30",
    },
    {
        "key": "New_York_Navajo_Nation_120",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "10",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "NAVAJO NATION",
        "trackcn": "印第安国度",
        "time": "120",
    },
    {
        "key": "New_York_Wall_Street_Ride_30",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "11",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "WALL STREET RIDE",
        "trackcn": "闯荡华尔街",
        "time": "30",
    },
    {
        "key": "New_York_Zeppelin_Race_60",
        "chapter": "2",
        "season": "Stars & Stripes",
        "race": "13",
        "modeen": "Classic",
        "locationen": "NEW YORK",
        "tracken": "ZEPPELIN RACE",
        "trackcn": "飞艇竞速",
        "time": "60",
    },
    {
        "key": "The_Caribbean_Paradise_Resort_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "2",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "PARADISE",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Auckland_UNDER_CONSTRUC_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "4",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "UNDER CONSTRUC",
        "trackcn": "建造施工",
        "time": "90",
    },
    {
        "key": "Auckland_OUT_OF_BOUNDS_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "4",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "OUT OF BOUNDS",
        "trackcn": "越界",
        "time": "90",
    },
    {
        "key": "Auckland_STARTING_GRID_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "4",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "STARTING GRID",
        "trackcn": "起跑排位",
        "time": "90",
    },
    {
        "key": "Auckland_Auckland_Track_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "4",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "AUCKLAND TRACK",
        "trackcn": "奥克兰赛道",
        "time": "90",
    },
    {
        "key": "Auckland_Straight_Sprint_30",
        "chapter": "2",
        "season": "Heatwave",
        "race": "5",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "STRAIGHT SPRINT",
        "trackcn": "起跑排位",
        "time": "30",
    },
    {
        "key": "Auckland_Industrial_Run_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "6",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "INDUSTRIAL RUN",
        "trackcn": "工业区竞速",
        "time": "90",
    },
    {
        "key": "Auckland_The_Circuit_120",
        "chapter": "2",
        "season": "Heatwave",
        "race": "7",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "THE CIRCUIT",
        "trackcn": "",
        "time": "120",
    },
    {
        "key": "Auckland_Straights_&_Hairpins_90",
        "chapter": "2",
        "season": "Heatwave",
        "race": "10",
        "modeen": "Time Attack",
        "locationen": "AUCKLAND",
        "tracken": "STRAIGHTS",
        "trackcn": "直道和弯道",
        "time": "90",
    },
    {
        "key": "Rome_Tiber_Stream_90",
        "chapter": "2",
        "season": "Class B Rookie",
        "race": "11",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "TIBER STREAM",
        "trackcn": "台伯河激流",
        "time": "90",
    },
    {
        "key": "Cairo_Nile_River_90",
        "chapter": "3",
        "season": "German Wheels",
        "race": "11",
        "modeen": "Classic",
        "locationen": "CAIRO",
        "tracken": "NILE RIVER",
        "trackcn": "尼罗河",
        "time": "90",
    },
    {
        "key": "San_Francisco_Rush_Minute_90",
        "chapter": "3",
        "season": "Lotus",
        "race": "1",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "RUSH MINUTE",
        "trackcn": "尖峰时刻",
        "time": "90",
    },
    {
        "key": "San_Francisco_Tunnel_Jam_90",
        "chapter": "3",
        "season": "Lotus",
        "race": "6",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "TUNNEL JAM",
        "trackcn": "拥堵隧道",
        "time": "90",
    },
    {
        "key": "San_Francisco_Bridge_View_120",
        "chapter": "3",
        "season": "American Extreme",
        "race": "16",
        "modeen": "Classic",
        "locationen": "SAN FRANCISCO",
        "tracken": "BRIDGE VIEW",
        "trackcn": "",
        "time": "120",
    },
    {
        "key": "The_Caribbean_Resort_Dash_30",
        "chapter": "3",
        "season": "Welcome to Paradise",
        "race": "1",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "RESORT DASH",
        "trackcn": "胜地冲刺",
        "time": "30",
    },
    {
        "key": "The_Caribbean_Hotel_Road_60",
        "chapter": "3",
        "season": "Welcome to Paradise",
        "race": "2",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "HOTEL ROAD",
        "trackcn": "酒店大道",
        "time": "60",
    },
    {
        "key": "The_Caribbean_Beach_Landing_90",
        "chapter": "3",
        "season": "Welcome to Paradise",
        "race": "3",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "BEACH LANDING",
        "trackcn": "海滩登陆",
        "time": "90",
    },
    {
        "key": "The_Caribbean_Hell_Vale_30",
        "chapter": "3",
        "season": "Welcome to Paradise",
        "race": "4",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "HELL VALE",
        "trackcn": "地狱谷",
        "time": "30",
    },
    {
        "key": "The_Caribbean_Island_Tour_120",
        "chapter": "3",
        "season": "Welcome to Paradise",
        "race": "6",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "ISLAND TOUR",
        "trackcn": "环岛之旅",
        "time": "120",
    },
    {
        "key": "Nevada_Hairpin_Sprint_60",
        "chapter": "3",
        "season": "Fire & Lightning",
        "race": "3",
        "modeen": "Classic",
        "locationen": "NEVADA",
        "tracken": "HAIRPIN SPRINT",
        "trackcn": "发夹弯冲刺",
        "time": "60",
    },
    {
        "key": "Osaka_Refined_Finish_90",
        "chapter": "3",
        "season": "Fire & Lightning",
        "race": "11",
        "modeen": "Time Attack",
        "locationen": "OSAKA",
        "tracken": "REFINED FINISH",
        "trackcn": "完美收尾",
        "time": "90",
    },
    {
        "key": "Osaka_Kita_Run_90",
        "chapter": "3",
        "season": "European Season",
        "race": "7",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "KITA RUN",
        "trackcn": "一路向北",
        "time": "90",
    },
    {
        "key": "Rome_Pantheon_Split_90",
        "chapter": "3",
        "season": "Mercedes",
        "race": "1",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "PANTHEON SPLIT",
        "trackcn": "万神殿岔路",
        "time": "90",
    },
    {
        "key": "Himalayas_Downhill_Run_90",
        "chapter": "3",
        "season": "Mercedes",
        "race": "2",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "DOWNHILL RUN",
        "trackcn": "山地速降",
        "time": "90",
    },
    {
        "key": "Rome_Ancient_Rome_90",
        "chapter": "3",
        "season": "Mercedes",
        "race": "5",
        "modeen": "Classic",
        "locationen": "ROME",
        "tracken": "ANCIENT ROME",
        "trackcn": "古罗马",
        "time": "90",
    },
    {
        "key": "Himalayas_Cave_Heat_90",
        "chapter": "3",
        "season": "Mercedes",
        "race": "6",
        "modeen": "Classic",
        "locationen": "HIMALAYAS",
        "tracken": "CAVE HEAT",
        "trackcn": "洞穴热浪",
        "time": "90",
    },
    {
        "key": "Auckland_Straight_Sprint_90",
        "chapter": "4",
        "season": "Electric Season",
        "race": "7",
        "modeen": "Classic",
        "locationen": "AUCKLAND",
        "tracken": "STRAIGHT SPRINT",
        "trackcn": "勇往直前",
        "time": "90",
    },
    {
        "key": "The_Caribbean_All-Inclusive_120",
        "chapter": "4",
        "season": "Italian Season",
        "race": "7",
        "modeen": "Hunted",
        "locationen": "THE CARIBBEAN",
        "tracken": "ALL-INCLUSIVE",
        "trackcn": "包罗万象",
        "time": "120",
    },
    {
        "key": "The_Caribbean_Pier_Pressure_90",
        "chapter": "4",
        "season": "Sun Racers",
        "race": "1",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "PIER PRESSURE",
        "trackcn": "桥墩压力",
        "time": "90",
    },
    {
        "key": "The_Caribbean_Islet_Race_30",
        "chapter": "4",
        "season": "Sun Racers",
        "race": "2",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "ISLET RACE",
        "trackcn": "小岛竞速",
        "time": "30",
    },
    {
        "key": "The_Caribbean_Thundering_Start_90",
        "chapter": "4",
        "season": "Sun Racers",
        "race": "3",
        "modeen": "Classic",
        "locationen": "THE CARIBBEAN",
        "tracken": "THUNDERING",
        "trackcn": "雷鸣之始",
        "time": "90",
    },
    {
        "key": "Osaka_Namba_Park_30",
        "chapter": "5",
        "season": "Tradition Meets Future",
        "race": "1",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "NAMBA PARK",
        "trackcn": "难波公园",
        "time": "30",
    },
    {
        "key": "Osaka_Moat_Finale_90",
        "chapter": "5",
        "season": "Tradition Meets Future",
        "race": "2",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "MOAT FINALE",
        "trackcn": "护城河决战",
        "time": "90",
    },
    {
        "key": "Osaka_Large_Hill_120",
        "chapter": "5",
        "season": "Tradition Meets Future",
        "race": "6",
        "modeen": "Hunted",
        "locationen": "OSAKA",
        "tracken": "LARGE HILL",
        "trackcn": "大型丘陵",
        "time": "120",
    },
    {
        "key": "Osaka_Welcome_to_Osaka_120",
        "chapter": "5",
        "season": "Tradition Meets Future",
        "race": "10",
        "modeen": "Classic",
        "locationen": "OSAKA",
        "tracken": "WELCOME TO OSAKA",
        "trackcn": "大阪欢迎你",
        "time": "120",
    },
    {
        "key": "Rome_The_Enchanted_Island_90",
        "chapter": "5",
        "season": "Ferrari",
        "race": "1",
        "modeen": "Time Attack",
        "locationen": "ROME",
        "tracken": "THE ENCHANTED ISLAND",
        "trackcn": "永恒之城",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Football_&_Politics_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "1",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "FOOTBALL & POLITICS",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Big_Passions_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "2",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "BIG PASSIONS",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Harbor_Run_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "3",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "HARBOR RUN",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Purple_Boulevard_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "4",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "PURPLE BOULEVARD",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Stadium_Lap_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "5",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "STADIUM LAP",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Through_the_Park_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "6",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "THROUGH THE PARK",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_New_City_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "7",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "NEW CITY",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Old_City_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "8",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "OLD CITY",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Buenos_Aires_Crosstown_Rivals_90",
        "chapter": "6",
        "season": "British Tour",
        "race": "9",
        "modeen": "Classic",
        "locationen": "BUENOS AIRES",
        "tracken": "CROSSTOWN RIVALS",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Fire_&_Ice_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "1",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "FIRE & ICE",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Volcano_Run_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "2",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "VOLCANO RUN",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Ice_Road_Circuit_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "3",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "ICE ROAD CIRCUIT",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Slippery_when_Icy_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "4",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "SLIPPERY WHEN",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Icy_Loop_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "5",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "ICY LOOP",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Coastal_Ice_90",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "6",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "COASTAL ICE",
        "trackcn": "",
        "time": "90",
    },
    {
        "key": "Greenland_Coastal_Loop_120",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "8",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "COASTAL LOOP",
        "trackcn": "",
        "time": "120",
    },
    {
        "key": "Greenland_Icebergs_&_Lava_120",
        "chapter": "6",
        "season": "Bring the Heat",
        "race": "9",
        "modeen": "Classic",
        "locationen": "GREENLAND",
        "tracken": "ICEBERGS & LAVA",
        "trackcn": "",
        "time": "120",
    },
]
