# Generated by Django 5.0.4 on 2024-06-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackingserver_template", "0002_alter_dagtemplate_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeartifact",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="codeartifact",
            name="path",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="dagtemplate",
            name="code_hash",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="dagtemplate",
            name="code_log_store",
            field=models.CharField(
                choices=[("s3", "S3"), ("local", "Local"), ("none", "None")], max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="dagtemplate",
            name="code_log_url",
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dagtemplate",
            name="code_version_info_type",
            field=models.CharField(choices=[("git", "Git"), ("ad_hoc", "Ad hoc")], max_length=1024),
        ),
        migrations.AlterField(
            model_name="nodetemplate",
            name="classifications",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="nodetemplate",
            name="dependencies",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="nodetemplate",
            name="dependency_specs",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="nodetemplate",
            name="name",
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="nodetemplate",
            name="output_type",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
