
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-14T15:15:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d06af067e4be71ea3b47593feb9be8ee7c37adc",
 "version": "2.7.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
