/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
N_LIB_PRIVATE TNimType NTIcint__Es1IiRCridTDsK3CygOFhw_;
N_LIB_PRIVATE TNimType NTIculong__hITEQB2A2GVtF9crzap8vUw_;
N_LIB_PRIVATE TNimType NTIcuint__dsXevNgTZ9aDgagoiXoktpA_;
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus2dot0dot0atslibatssystematsctypesdotnim_DatInit000)(void) {
NTIcint__Es1IiRCridTDsK3CygOFhw_.size = sizeof(int);
NTIcint__Es1IiRCridTDsK3CygOFhw_.align = NIM_ALIGNOF(int);
NTIcint__Es1IiRCridTDsK3CygOFhw_.kind = 34;
NTIcint__Es1IiRCridTDsK3CygOFhw_.base = 0;
NTIcint__Es1IiRCridTDsK3CygOFhw_.flags = 3;
NTIculong__hITEQB2A2GVtF9crzap8vUw_.size = sizeof(unsigned long);
NTIculong__hITEQB2A2GVtF9crzap8vUw_.align = NIM_ALIGNOF(unsigned long);
NTIculong__hITEQB2A2GVtF9crzap8vUw_.kind = 43;
NTIculong__hITEQB2A2GVtF9crzap8vUw_.base = 0;
NTIculong__hITEQB2A2GVtF9crzap8vUw_.flags = 3;
NTIcuint__dsXevNgTZ9aDgagoiXoktpA_.size = sizeof(unsigned int);
NTIcuint__dsXevNgTZ9aDgagoiXoktpA_.align = NIM_ALIGNOF(unsigned int);
NTIcuint__dsXevNgTZ9aDgagoiXoktpA_.kind = 43;
NTIcuint__dsXevNgTZ9aDgagoiXoktpA_.base = 0;
NTIcuint__dsXevNgTZ9aDgagoiXoktpA_.flags = 3;
}

