/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ;
typedef struct tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA;
typedef struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ tySequence__7s5HyddQ0f9bxMNILHrXwJQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g tyTuple__kuMQ1fbjJlHtwKTmBGAe6g;
typedef struct tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw;
typedef struct tySequence__XAZNH1jPFL9aAWN7LeA3eng tySequence__XAZNH1jPFL9aAWN7LeA3eng;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
struct TGenericSeq {
	NI len;
	NI reserved;
};
typedef NU16 tyEnum_component_kind__hDjVFZyz7iZWUbN9bi4D1CA;
struct tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg {
	NI16 x;
	NI16 y;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA {
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ* data;
	NI counter;
};
struct tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ {
	tyEnum_component_kind__hDjVFZyz7iZWUbN9bi4D1CA kind;
	tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg position;
	tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg custom_displacement;
	NU8 rotation;
	NI8 real_offset;
	NI permanent_id;
	NimStringDesc* custom_string;
	NI custom_id;
	NU64 setting1;
	NU64 setting2;
	tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA selected_programs;
	NI16 ui_order;
};
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct tyTuple__kuMQ1fbjJlHtwKTmBGAe6g {
NI Field0;
NI Field1;
NimStringDesc* Field2;
};
typedef NU8 tyEnum_wire_kind__lpUm9cpOexnuxkIZLrG7vjA;
struct tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw {
	tySequence__XAZNH1jPFL9aAWN7LeA3eng* path;
	tyEnum_wire_kind__lpUm9cpOexnuxkIZLrG7vjA kind;
	NU8 color;
	NimStringDesc* comment;
};
typedef NU8 tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w;
typedef tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg tyArray__O6Bneb1lztR7ZBgQNDWnBg[8];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tySequence__7s5HyddQ0f9bxMNILHrXwJQ {
  TGenericSeq Sup;
  tyTuple__kuMQ1fbjJlHtwKTmBGAe6g data[SEQ_DECL_SIZE];
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__XAZNH1jPFL9aAWN7LeA3eng {
  TGenericSeq Sup;
  tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tySequence__7s5HyddQ0f9bxMNILHrXwJQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NU16, get_u16__common_u442)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, get_int__common_u374)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s_p0, TNimType* typ_p1);
N_LIB_PRIVATE N_NIMCALL(NU8, get_u8__common_u462)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NI16, get_i16__common_u458)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1);
N_LIB_PRIVATE N_NIMCALL(NU32, get_u32__common_u418)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_u16__common_u653)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU16 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_int__common_u548)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NI input_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u85)(NimStringDesc* msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, add_u8__common_u691)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU8 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_i16__common_u672)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NI16 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_u32__common_u618)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU32 input_p1);
N_LIB_PRIVATE N_NIMCALL(void, add_point__common_u734)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg input_p1);
static N_INLINE(NI, find__common_u1300)(tyArray__O6Bneb1lztR7ZBgQNDWnBg a_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg item_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___common_u1373)(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg x_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, minus___common_u358)(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg a_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg b_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE TNimType NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_;
N_LIB_PRIVATE TNimType NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_;
N_LIB_PRIVATE TNimType NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_;
extern TNimType NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_;
extern TNimType NTIuint56__k3HXouOuhqAKq0dx450lXQ_;
extern TNimType NTIint56__chXunH2dwinSkhpA6JnsXw_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIuint5452__wMtfD88jmrPZwfzTH9c8e9cA_;
N_LIB_PRIVATE TNimType NTItable__N0H9bDibSHG9c6NYdKk0RfmA_;
N_LIB_PRIVATE TNimType NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_;
N_LIB_PRIVATE TNimType NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_;
N_LIB_PRIVATE TNimType NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_;
extern TNimType NTIseqLpointT__XAZNH1jPFL9aAWN7LeA3eng_;
N_LIB_PRIVATE TNimType NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_;
extern TNimType NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_;
extern TNimType NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_;
STRING_LITERAL(TM__AZJHBAzoQYZ8EayTGp7UeA_42, "iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__AZJHBAzoQYZ8EayTGp7UeA_44, "iterators.nim(264, 11) `len(a) == L` the length of the string changed while iterating over it", 93);
N_LIB_PRIVATE NIM_CONST tyArray__O6Bneb1lztR7ZBgQNDWnBg DIRECTIONS__common_u278 = {{((NI16)1), ((NI16)0)}
,
{((NI16)1), ((NI16)1)}
,
{((NI16)0), ((NI16)1)}
,
{((NI16)-1), ((NI16)1)}
,
{((NI16)-1), ((NI16)0)}
,
{((NI16)-1), ((NI16)-1)}
,
{((NI16)0), ((NI16)-1)}
,
{((NI16)1), ((NI16)-1)}
}
;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, get_int__common_u374)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NI result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_2;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_3;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_4;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_5;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_6;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_7;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_8;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_9;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_10;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_11;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_12;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_13;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_14;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_15;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_16;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_17;
	result = (NI)0;
	if (nimAddInt((*i_p1), ((NI)0), &TM__AZJHBAzoQYZ8EayTGp7UeA_2)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_2) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_2) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_2),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_3)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_3) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_3) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_3),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_2)]))) << (NU64)(((NI)0))), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_3)]))) << (NU64)(((NI)8))), &TM__AZJHBAzoQYZ8EayTGp7UeA_4)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)2), &TM__AZJHBAzoQYZ8EayTGp7UeA_5)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_5) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_5) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_5),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_4), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_5)]))) << (NU64)(((NI)16))), &TM__AZJHBAzoQYZ8EayTGp7UeA_6)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)3), &TM__AZJHBAzoQYZ8EayTGp7UeA_7)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_7) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_7) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_7),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_6), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_7)]))) << (NU64)(((NI)24))), &TM__AZJHBAzoQYZ8EayTGp7UeA_8)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)4), &TM__AZJHBAzoQYZ8EayTGp7UeA_9)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_9) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_9) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_9),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_8), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_9)]))) << (NU64)(((NI)32))), &TM__AZJHBAzoQYZ8EayTGp7UeA_10)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)5), &TM__AZJHBAzoQYZ8EayTGp7UeA_11)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_11) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_11) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_11),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_10), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_11)]))) << (NU64)(((NI)40))), &TM__AZJHBAzoQYZ8EayTGp7UeA_12)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)6), &TM__AZJHBAzoQYZ8EayTGp7UeA_13)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_13) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_13) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_13),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_12), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_13)]))) << (NU64)(((NI)48))), &TM__AZJHBAzoQYZ8EayTGp7UeA_14)) { raiseOverflow(); 	};
	if (nimAddInt((*i_p1), ((NI)7), &TM__AZJHBAzoQYZ8EayTGp7UeA_15)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_15) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_15) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_15),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_14), (NI)((NU64)(((NI) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_15)]))) << (NU64)(((NI)56))), &TM__AZJHBAzoQYZ8EayTGp7UeA_16)) { raiseOverflow(); 	};
	result = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_16);
	if (nimAddInt((*i_p1), ((NI)8), &TM__AZJHBAzoQYZ8EayTGp7UeA_17)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_17);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, get_u32__common_u418)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NU32 result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_18;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_19;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_20;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_21;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_22;
	result = (NU32)0;
	if (nimAddInt((*i_p1), ((NI)0), &TM__AZJHBAzoQYZ8EayTGp7UeA_18)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_18) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_18) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_18),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_19)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_19) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_19) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_19),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((*i_p1), ((NI)2), &TM__AZJHBAzoQYZ8EayTGp7UeA_20)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_20) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_20) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_20),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((*i_p1), ((NI)3), &TM__AZJHBAzoQYZ8EayTGp7UeA_21)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_21) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_21) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_21),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	result = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_18)]))) << (NU64)(((NI)0)))) + (NU32)((NU32)((NU64)(((NU32) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_19)]))) << (NU64)(((NI)8)))))) + (NU32)((NU32)((NU64)(((NU32) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_20)]))) << (NU64)(((NI)16)))))) + (NU32)((NU32)((NU64)(((NU32) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_21)]))) << (NU64)(((NI)24)))));
	if (nimAddInt((*i_p1), ((NI)4), &TM__AZJHBAzoQYZ8EayTGp7UeA_22)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_22);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, get_bool__common_u366)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NIM_BOOL result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_23;
	result = (NIM_BOOL)0;
	if ((*i_p1) < 0 || (*i_p1) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((*i_p1),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	result = !((input_p0->data[(*i_p1)] == ((NU8)0)));
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_23)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_23);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, get_u8__common_u462)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NU8 result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_24;
	result = (NU8)0;
	if ((*i_p1) < 0 || (*i_p1) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((*i_p1),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	result = input_p0->data[(*i_p1)];
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_24)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_24);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU16, get_u16__common_u442)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NU16 result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_25;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_26;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_27;
	result = (NU16)0;
	if (nimAddInt((*i_p1), ((NI)0), &TM__AZJHBAzoQYZ8EayTGp7UeA_25)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_25) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_25) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_25),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_26)) { raiseOverflow(); 	};
	if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_26) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_26) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_26),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	result = (NU16)((NU16)((NU16)((NU64)(((NU16) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_25)]))) << (NU64)(((NI)0)))) + (NU16)((NU16)((NU64)(((NU16) (input_p0->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_26)]))) << (NU64)(((NI)8)))));
	if (nimAddInt((*i_p1), ((NI)2), &TM__AZJHBAzoQYZ8EayTGp7UeA_27)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_27);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI8, get_i8__common_u470)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NI8 result;
	NI TM__AZJHBAzoQYZ8EayTGp7UeA_28;
	result = (NI8)0;
	if ((*i_p1) < 0 || (*i_p1) >= (input_p0 ? input_p0->Sup.len : 0)){ raiseIndexError2((*i_p1),(input_p0 ? input_p0->Sup.len : 0)-1); 	}
	result = ((NI8) (input_p0->data[(*i_p1)]));
	if (nimAddInt((*i_p1), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_28)) { raiseOverflow(); 	};
	(*i_p1) = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_28);
	return result;
}
static N_NIMCALL(void, Marker_tySequence__7s5HyddQ0f9bxMNILHrXwJQ)(void* p, NI op) {
	tySequence__7s5HyddQ0f9bxMNILHrXwJQ* a;
	NI T1_;
	a = (tySequence__7s5HyddQ0f9bxMNILHrXwJQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}
N_LIB_PRIVATE N_NIMCALL(NI16, get_i16__common_u458)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NI16 result;
	NU16 T1_;
	result = (NI16)0;
	T1_ = (NU16)0;
	T1_ = get_u16__common_u442(input_p0, i_p1);
	result = ((NI16) (T1_));
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, plus___common_u337)(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg a_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg b_p1) {
	tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg result;
{	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	result.x = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.x))) + (NU16)(((NU16) (b_p1.x))))));
	result.y = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.y))) + (NU16)(((NU16) (b_p1.y))))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, get_seq_int__common_u517)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* result;
	NU16 len;
	NU16 j;
	result = NIM_NIL;
	len = get_u16__common_u442(input_p0, i_p1);
	j = ((NU16)0);
	{
		while (1) {
			NI T3_;
			NI T4_;
			if (!((NU16)(j) < (NU16)(len))) goto LA2;
			T3_ = (NI)0;
			T3_ = get_int__common_u374(input_p0, i_p1);
			result = (tySequence__qwqHTkRvwhrRyENtudHQ7g*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_));
			T4_ = result->Sup.len++;
			result->data[T4_] = T3_;
			j += ((NI)1);
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, get_string__common_u531)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NimStringDesc* result;
	NU16 len;
	NU16 j;
	result = NIM_NIL;
	len = get_u16__common_u442(input_p0, i_p1);
	j = ((NU16)0);
	{
		while (1) {
			NU8 T3_;
			if (!((NU16)(j) < (NU16)(len))) goto LA2;
			T3_ = (NU8)0;
			T3_ = get_u8__common_u462(input_p0, i_p1);
			result = addChar(result, ((NIM_CHAR) (((NI) (T3_)))));
			j += ((NI)1);
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, get_point__common_u498)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg result;
{	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	result.x = get_i16__common_u458(input_p0, i_p1);
	result.y = get_i16__common_u458(input_p0, i_p1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*, get_seq_u8__common_u502)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1, NIM_BOOL bits32_p2) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* result;
	NI len;
	NI j;
	result = NIM_NIL;
	len = ((NI)0);
	{
		NU32 T5_;
		if (!bits32_p2) goto LA3_;
		T5_ = (NU32)0;
		T5_ = get_u32__common_u418(input_p0, i_p1);
		len = ((NI) (T5_));
	}
	goto LA1_;
LA3_: ;
	{
		NU16 T7_;
		T7_ = (NU16)0;
		T7_ = get_u16__common_u442(input_p0, i_p1);
		len = ((NI) (T7_));
	}
LA1_: ;
	j = ((NI)0);
	{
		while (1) {
			NU8 T10_;
			NI T11_;
			NI TM__AZJHBAzoQYZ8EayTGp7UeA_40;
			if (!(j < len)) goto LA9;
			T10_ = (NU8)0;
			T10_ = get_u8__common_u462(input_p0, i_p1);
			result = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_));
			T11_ = result->Sup.len++;
			result->data[T11_] = T10_;
			if (nimAddInt(j, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_40)) { raiseOverflow(); 			};
			j = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_40);
		} LA9: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, get_u64__common_u414)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	NU64 result;
	NI T1_;
	result = (NU64)0;
	T1_ = (NI)0;
	T1_ = get_int__common_u374(input_p0, i_p1);
	result = ((NU64) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w, get_sync_state__common_u478)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p0, NI* i_p1) {
	tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w result;
	NU8 T1_;
	result = (tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w)0;
	T1_ = (NU8)0;
	T1_ = get_u8__common_u462(input_p0, i_p1);
	if ((T1_) < ((tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w)0) || (T1_) > ((tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w)2)){ raiseRangeErrorI(T1_, ((tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w)0), ((tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w)2)); 	}
	result = ((tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add_int__common_u548)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NI input_p1) {
	NI T1_;
	NI T2_;
	NI T3_;
	NI T4_;
	NI T5_;
	NI T6_;
	NI T7_;
	NI T8_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)0))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T2_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T2_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)8))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T3_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T3_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)16))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T4_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T4_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)24))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T5_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T5_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)32))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T6_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T6_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)40))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T7_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T7_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)48))) & ((NI)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T8_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T8_] = ((NU8) ((NI)((NI)((NI64)(input_p1) >> (NU64)(((NI)56))) & ((NI)255))));
}
N_LIB_PRIVATE N_NIMCALL(void, add_u32__common_u618)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU32 input_p1) {
	NI T1_;
	NI T2_;
	NI T3_;
	NI T4_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)0))) & ((NU32)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T2_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T2_] = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)8))) & ((NU32)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T3_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T3_] = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)16))) & ((NU32)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T4_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T4_] = ((NU8) ((NU32)((NU32)((NU32)(input_p1) >> (NU64)(((NI)24))) & ((NU32)255))));
}
N_LIB_PRIVATE N_NIMCALL(void, add_bool__common_u541)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NIM_BOOL input_p1) {
	NI T1_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) (input_p1));
}
N_LIB_PRIVATE N_NIMCALL(void, add_u16__common_u653)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU16 input_p1) {
	NI T1_;
	NI T2_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) ((NU16)((NU16)((NU16)(input_p1) >> (NU64)(((NI)0))) & ((NU16)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T2_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T2_] = ((NU8) ((NU16)((NU16)((NU16)(input_p1) >> (NU64)(((NI)8))) & ((NU16)255))));
}
N_LIB_PRIVATE N_NIMCALL(void, add_seq_int__common_u786)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g* input_p1) {
	NI T1_;
	T1_ = (input_p1 ? input_p1->Sup.len : 0);
	add_u16__common_u653(arr_p0, ((NU16) (T1_)));
	{
		NI* i;
		NI i_2;
		NI L;
		NI T3_;
		i = (NI*)0;
		i_2 = ((NI)0);
		T3_ = (input_p1 ? input_p1->Sup.len : 0);
		L = T3_;
		{
			while (1) {
				NI TM__AZJHBAzoQYZ8EayTGp7UeA_41;
				if (!(i_2 < L)) goto LA5;
				if (i_2 < 0 || i_2 >= (input_p1 ? input_p1->Sup.len : 0)){ raiseIndexError2(i_2,(input_p1 ? input_p1->Sup.len : 0)-1); 				}
				i = (&input_p1->data[i_2]);
				add_int__common_u548(arr_p0, (*i));
				if (nimAddInt(i_2, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_41)) { raiseOverflow(); 				};
				i_2 = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_41);
				{
					NI T8_;
					T8_ = (input_p1 ? input_p1->Sup.len : 0);
					if (!!((T8_ == L))) goto LA9_;
					failedAssertImpl__stdZassertions_u85(((NimStringDesc*) &TM__AZJHBAzoQYZ8EayTGp7UeA_42));
				}
LA9_: ;
			} LA5: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, add_u8__common_u691)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU8 input_p1) {
	NI T1_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = input_p1;
}
N_LIB_PRIVATE N_NIMCALL(void, add_string__common_u892)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NimStringDesc* input_p1) {
	add_u16__common_u653(arr_p0, ((NU16) ((input_p1 ? input_p1->Sup.len : 0))));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI)0);
		L = (input_p1 ? input_p1->Sup.len : 0);
		{
			while (1) {
				NI TM__AZJHBAzoQYZ8EayTGp7UeA_43;
				if (!(i < L)) goto LA3;
				if (i < 0 || i >= (input_p1 ? input_p1->Sup.len : 0)){ raiseIndexError2(i,(input_p1 ? input_p1->Sup.len : 0)-1); 				}
				c = input_p1->data[i];
				add_u8__common_u691(arr_p0, ((NU8) (((NU8)(c)))));
				if (nimAddInt(i, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_43)) { raiseOverflow(); 				};
				i = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_43);
				{
					if (!!(((input_p1 ? input_p1->Sup.len : 0) == L))) goto LA6_;
					failedAssertImpl__stdZassertions_u85(((NimStringDesc*) &TM__AZJHBAzoQYZ8EayTGp7UeA_44));
				}
LA6_: ;
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, add_i16__common_u672)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NI16 input_p1) {
	NI T1_;
	NI T2_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) ((NI16)((NI16)((NI64)(input_p1) >> (NU64)(((NI)0))) & ((NI16)255))));
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T2_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T2_] = ((NU8) ((NI16)((NI16)((NI64)(input_p1) >> (NU64)(((NI)8))) & ((NI16)255))));
}
N_LIB_PRIVATE N_NIMCALL(void, add_point__common_u734)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg input_p1) {
	add_i16__common_u672(arr_p0, input_p1.x);
	add_i16__common_u672(arr_p0, input_p1.y);
}
N_LIB_PRIVATE N_NIMCALL(void, add_sync_state__common_u723)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tyEnum_sync_state__QT9a2TFyQi9cGTovaucQ9ct4w input_p1) {
	NI T1_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) (input_p1));
}
N_LIB_PRIVATE N_NIMCALL(void, add_seq_u8__common_u737)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* input_p1, NIM_BOOL bits32_p2) {
	{
		NI T5_;
		if (!bits32_p2) goto LA3_;
		T5_ = (input_p1 ? input_p1->Sup.len : 0);
		add_u32__common_u618(arr_p0, ((NU32) (T5_)));
	}
	goto LA1_;
LA3_: ;
	{
		NI T7_;
		T7_ = (input_p1 ? input_p1->Sup.len : 0);
		add_u16__common_u653(arr_p0, ((NU16) (T7_)));
	}
LA1_: ;
	{
		NU8* i;
		NI i_2;
		NI L;
		NI T9_;
		i = (NU8*)0;
		i_2 = ((NI)0);
		T9_ = (input_p1 ? input_p1->Sup.len : 0);
		L = T9_;
		{
			while (1) {
				NI TM__AZJHBAzoQYZ8EayTGp7UeA_45;
				if (!(i_2 < L)) goto LA11;
				if (i_2 < 0 || i_2 >= (input_p1 ? input_p1->Sup.len : 0)){ raiseIndexError2(i_2,(input_p1 ? input_p1->Sup.len : 0)-1); 				}
				i = (&input_p1->data[i_2]);
				add_u8__common_u691(arr_p0, (*i));
				if (nimAddInt(i_2, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_45)) { raiseOverflow(); 				};
				i_2 = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_45);
				{
					NI T14_;
					T14_ = (input_p1 ? input_p1->Sup.len : 0);
					if (!!((T14_ == L))) goto LA15_;
					failedAssertImpl__stdZassertions_u85(((NimStringDesc*) &TM__AZJHBAzoQYZ8EayTGp7UeA_42));
				}
LA15_: ;
			} LA11: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, add_component_kind__common_u705)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tyEnum_component_kind__hDjVFZyz7iZWUbN9bi4D1CA input_p1) {
	add_u16__common_u653(arr_p0, ((NU16) (input_p1)));
}
N_LIB_PRIVATE N_NIMCALL(void, add_u64__common_u615)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, NU64 input_p1) {
	add_int__common_u548(arr_p0, ((NI) (input_p1)));
}
N_LIB_PRIVATE N_NIMCALL(void, add_wire_kind__common_u712)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tyEnum_wire_kind__lpUm9cpOexnuxkIZLrG7vjA input_p1) {
	NI T1_;
	unsureAsgnRef((void**) (&(*arr_p0)), (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV3((TGenericSeq*)((*arr_p0)), (&NTIseqLuint56T__6H5Oh5UUvVCLiakt9aTwtUQ_)));
	T1_ = (*arr_p0)->Sup.len++;
	(*arr_p0)->data[T1_] = ((NU8) (input_p1));
}
static N_INLINE(NI, find__common_u1300)(tyArray__O6Bneb1lztR7ZBgQNDWnBg a_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg item_p1) {
	NI result;
{	result = (NI)0;
	result = ((NI)0);
	{
		tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg i;
		NI i_2;
		nimZeroMem((void*)(&i), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__AZJHBAzoQYZ8EayTGp7UeA_46;
				NI TM__AZJHBAzoQYZ8EayTGp7UeA_47;
				i = a_p0[(i_2)- 0];
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = eqeq___common_u1373(i, item_p1);
					if (!T6_) goto LA7_;
					goto BeforeRet_;
				}
LA7_: ;
				if (nimAddInt(result, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_46)) { raiseOverflow(); 				};
				result = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_46);
				{
					if (!(((NI)7) <= ((NI) (i_2)))) goto LA11_;
					goto LA2;
				}
LA11_: ;
				if (nimAddInt(i_2, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_47)) { raiseOverflow(); 				};
				if (TM__AZJHBAzoQYZ8EayTGp7UeA_47 < 0 || TM__AZJHBAzoQYZ8EayTGp7UeA_47 > 7){ raiseOverflow(); 				}
				i_2 = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_47);
			}
		} LA2: ;
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, minus___common_u358)(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg a_p0, tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg b_p1) {
	tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg result;
{	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	nimZeroMem((void*)(&result), sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg));
	result.x = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.x))) - (NU16)(((NU16) (b_p1.x))))));
	result.y = ((NI16) ((NU16)((NU16)(((NU16) (a_p0.y))) - (NU16)(((NU16) (b_p1.y))))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add_path__common_u1293)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ** arr_p0, tySequence__XAZNH1jPFL9aAWN7LeA3eng* path_p1) {
	NI offset;
{	if (((NI)0) < 0 || ((NI)0) >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2(((NI)0),(path_p1 ? path_p1->Sup.len : 0)-1); 	}
	add_point__common_u734(arr_p0, path_p1->data[((NI)0)]);
	offset = ((NI)0);
	{
		while (1) {
			NI T3_;
			NI original_direction;
			NI TM__AZJHBAzoQYZ8EayTGp7UeA_48;
			tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg T4_;
			NI max_length;
			NI T14_;
			NI TM__AZJHBAzoQYZ8EayTGp7UeA_49;
			NI length;
			NI direction;
			NU8 segment;
			NI TM__AZJHBAzoQYZ8EayTGp7UeA_54;
			T3_ = ((path_p1 ? path_p1->Sup.len : 0)-1);
			if (!(offset < T3_)) goto LA2;
			if (nimAddInt(offset, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_48)) { raiseOverflow(); 			};
			if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_48) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_48) >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_48),(path_p1 ? path_p1->Sup.len : 0)-1); 			}
			if (offset < 0 || offset >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2(offset,(path_p1 ? path_p1->Sup.len : 0)-1); 			}
			T4_ = minus___common_u358(path_p1->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_48)], path_p1->data[offset]);
			original_direction = find__common_u1300(DIRECTIONS__common_u278, T4_);
			{
				if (!(original_direction == ((NI)-1))) goto LA7_;
				{
					NI T11_;
					T11_ = (path_p1 ? path_p1->Sup.len : 0);
					if (!(T11_ == ((NI)2))) goto LA12_;
					add_u8__common_u691(arr_p0, ((NU8)32));
					if (((NI)1) < 0 || ((NI)1) >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2(((NI)1),(path_p1 ? path_p1->Sup.len : 0)-1); 					}
					add_point__common_u734(arr_p0, path_p1->data[((NI)1)]);
					goto BeforeRet_;
				}
LA12_: ;
				goto LA1;
			}
LA7_: ;
			T14_ = ((path_p1 ? path_p1->Sup.len : 0)-1);
			if (nimSubInt(T14_, offset, &TM__AZJHBAzoQYZ8EayTGp7UeA_49)) { raiseOverflow(); 			};
			max_length = (((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_49) <= ((NI)31)) ? (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_49) : ((NI)31));
			length = ((NI)1);
			direction = original_direction;
			{
				while (1) {
					NI TM__AZJHBAzoQYZ8EayTGp7UeA_50;
					NI TM__AZJHBAzoQYZ8EayTGp7UeA_51;
					NI TM__AZJHBAzoQYZ8EayTGp7UeA_52;
					tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg T17_;
					NI TM__AZJHBAzoQYZ8EayTGp7UeA_53;
					if (!(length < max_length)) goto LA16;
					if (nimAddInt(offset, length, &TM__AZJHBAzoQYZ8EayTGp7UeA_50)) { raiseOverflow(); 					};
					if (nimAddInt((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_50), ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_51)) { raiseOverflow(); 					};
					if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_51) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_51) >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_51),(path_p1 ? path_p1->Sup.len : 0)-1); 					}
					if (nimAddInt(offset, length, &TM__AZJHBAzoQYZ8EayTGp7UeA_52)) { raiseOverflow(); 					};
					if ((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_52) < 0 || (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_52) >= (path_p1 ? path_p1->Sup.len : 0)){ raiseIndexError2((NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_52),(path_p1 ? path_p1->Sup.len : 0)-1); 					}
					T17_ = minus___common_u358(path_p1->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_51)], path_p1->data[(NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_52)]);
					direction = find__common_u1300(DIRECTIONS__common_u278, T17_);
					{
						if (!!((direction == original_direction))) goto LA20_;
						goto LA15;
					}
LA20_: ;
					if (nimAddInt(length, ((NI)1), &TM__AZJHBAzoQYZ8EayTGp7UeA_53)) { raiseOverflow(); 					};
					length = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_53);
				} LA16: ;
			} LA15: ;
			segment = ((NU8) ((NI)((NI)((NU64)(original_direction) << (NU64)(((NI)5))) | length)));
			add_u8__common_u691(arr_p0, segment);
			if (nimAddInt(offset, length, &TM__AZJHBAzoQYZ8EayTGp7UeA_54)) { raiseOverflow(); 			};
			offset = (NI)(TM__AZJHBAzoQYZ8EayTGp7UeA_54);
		} LA2: ;
	} LA1: ;
	add_u8__common_u691(arr_p0, ((NU8)0));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmcommondotnim_DatInit000)(void) {
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[12];
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_30_258[258];
NI TM__AZJHBAzoQYZ8EayTGp7UeA_32;
static char* NIM_CONST TM__AZJHBAzoQYZ8EayTGp7UeA_31[258] = {
"Error", 
"Off", 
"On", 
"Buffer1", 
"Not", 
"And", 
"And3", 
"Nand", 
"Or", 
"Or3", 
"Nor", 
"Xor", 
"Xnor", 
"Counter8", 
"VirtualCounter8", 
"Counter64", 
"VirtualCounter64", 
"Ram8", 
"VirtualRam8", 
"DELETED_0", 
"DELETED_1", 
"DELETED_17", 
"DELETED_18", 
"Register8", 
"VirtualRegister8", 
"Register8Red", 
"VirtualRegister8Red", 
"Register8RedPlus", 
"VirtualRegister8RedPlus", 
"Register64", 
"VirtualRegister64", 
"Switch8", 
"Mux8", 
"Decoder1", 
"Decoder3", 
"Constant8", 
"Not8", 
"Or8", 
"And8", 
"Xor8", 
"Equal8", 
"DELETED_2", 
"DELETED_3", 
"Neg8", 
"Add8", 
"Mul8", 
"Splitter8", 
"Maker8", 
"Splitter64", 
"Maker64", 
"FullAdder", 
"BitMemory", 
"VirtualBitMemory", 
"DELETED_10", 
"Decoder2", 
"Timing", 
"NoteSound", 
"DELETED_4", 
"DELETED_5", 
"Keyboard", 
"FileLoader", 
"Halt", 
"WireCluster", 
"LevelScreen", 
"Program8_1", 
"Program8_1Red", 
"DELETED_6", 
"DELETED_7", 
"Program8_4", 
"LevelGate", 
"Input1", 
"LevelInput2Pin", 
"LevelInput3Pin", 
"LevelInput4Pin", 
"LevelInputConditions", 
"Input8", 
"Input64", 
"LevelInputCode", 
"LevelInputArch", 
"Output1", 
"LevelOutput1Sum", 
"LevelOutput1Car", 
"DELETED_8", 
"DELETED_9", 
"LevelOutput2Pin", 
"LevelOutput3Pin", 
"LevelOutput4Pin", 
"Output8", 
"Output64", 
"LevelOutputArch", 
"LevelOutputCounter", 
"DELETED_11", 
"Custom", 
"VirtualCustom", 
"Program", 
"DelayLine1", 
"VirtualDelayLine1", 
"Console", 
"Shl8", 
"Shr8", 
"Constant64", 
"Not64", 
"Or64", 
"And64", 
"Xor64", 
"Neg64", 
"Add64", 
"Mul64", 
"Equal64", 
"LessU64", 
"LessI64", 
"Shl64", 
"Shr64", 
"Mux64", 
"Switch64", 
"ProbeMemoryBit", 
"ProbeMemoryWord", 
"AndOrLatch", 
"NandNandLatch", 
"NorNorLatch", 
"LessU8", 
"LessI8", 
"DotMatrixDisplay", 
"SegmentDisplay", 
"Input16", 
"Input32", 
"Output16", 
"Output32", 
"DELETED_12", 
"DELETED_13", 
"DELETED_14", 
"DELETED_15", 
"DELETED_16", 
"Buffer8", 
"Buffer16", 
"Buffer32", 
"Buffer64", 
"ProbeWireBit", 
"ProbeWireWord", 
"Switch1", 
"Output1z", 
"Output8z", 
"Output16z", 
"Output32z", 
"Output64z", 
"Constant16", 
"Not16", 
"Or16", 
"And16", 
"Xor16", 
"Neg16", 
"Add16", 
"Mul16", 
"Equal16", 
"LessU16", 
"LessI16", 
"Shl16", 
"Shr16", 
"Mux16", 
"Switch16", 
"Splitter16", 
"Maker16", 
"Register16", 
"VirtualRegister16", 
"Counter16", 
"VirtualCounter16", 
"Constant32", 
"Not32", 
"Or32", 
"And32", 
"Xor32", 
"Neg32", 
"Add32", 
"Mul32", 
"Equal32", 
"LessU32", 
"LessI32", 
"Shl32", 
"Shr32", 
"Mux32", 
"Switch32", 
"Splitter32", 
"Maker32", 
"Register32", 
"VirtualRegister32", 
"Counter32", 
"VirtualCounter32", 
"LevelOutput8z", 
"Nand8", 
"Nor8", 
"Xnor8", 
"Nand16", 
"Nor16", 
"Xnor16", 
"Nand32", 
"Nor32", 
"Xnor32", 
"Nand64", 
"Nor64", 
"Xnor64", 
"Ram", 
"VirtualRam", 
"RamLatency", 
"VirtualRamLatency", 
"RamFast", 
"VirtualRamFast", 
"Rom", 
"VirtualRom", 
"SolutionRom", 
"VirtualSolutionRom", 
"DelayLine8", 
"VirtualDelayLine8", 
"DelayLine16", 
"VirtualDelayLine16", 
"DelayLine32", 
"VirtualDelayLine32", 
"DelayLine64", 
"VirtualDelayLine64", 
"RamDualLoad", 
"VirtualRamDualLoad", 
"Hdd", 
"VirtualHdd", 
"Network", 
"Rol8", 
"Rol16", 
"Rol32", 
"Rol64", 
"Ror8", 
"Ror16", 
"Ror32", 
"Ror64", 
"IndexerBit", 
"IndexerByte", 
"DivMod8", 
"DivMod16", 
"DivMod32", 
"DivMod64", 
"SpriteDisplay", 
"ConfigDelay", 
"Clock", 
"LevelInput1", 
"LevelInput8", 
"LevelOutput1", 
"LevelOutput8", 
"Ashr8", 
"Ashr16", 
"Ashr32", 
"Ashr64", 
"Bidirectional1", 
"VirtualBidirectional1", 
"Bidirectional8", 
"VirtualBidirectional8", 
"Bidirectional16", 
"VirtualBidirectional16", 
"Bidirectional32", 
"VirtualBidirectional32", 
"Bidirectional64", 
"VirtualBidirectional64"};
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_33_2[2];
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_34_2[2];
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_35_3[3];
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[4];
static TNimNode* TM__AZJHBAzoQYZ8EayTGp7UeA_37_5[5];
NI TM__AZJHBAzoQYZ8EayTGp7UeA_39;
static char* NIM_CONST TM__AZJHBAzoQYZ8EayTGp7UeA_38[5] = {
"wk_1", 
"wk_8", 
"wk_16", 
"wk_32", 
"wk_64"};
static TNimNode TM__AZJHBAzoQYZ8EayTGp7UeA_0[293];
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.size = sizeof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ);
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.align = NIM_ALIGNOF(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ);
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.kind = 18;
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.base = 0;
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.flags = 2;
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[0] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[1];
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.size = sizeof(tyEnum_component_kind__hDjVFZyz7iZWUbN9bi4D1CA);
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.align = NIM_ALIGNOF(tyEnum_component_kind__hDjVFZyz7iZWUbN9bi4D1CA);
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.kind = 14;
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.base = 0;
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.flags = 3;
for (TM__AZJHBAzoQYZ8EayTGp7UeA_32 = 0; TM__AZJHBAzoQYZ8EayTGp7UeA_32 < 258; TM__AZJHBAzoQYZ8EayTGp7UeA_32++) {
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_32+2].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_32+2].offset = TM__AZJHBAzoQYZ8EayTGp7UeA_32;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_32+2].name = TM__AZJHBAzoQYZ8EayTGp7UeA_31[TM__AZJHBAzoQYZ8EayTGp7UeA_32];
TM__AZJHBAzoQYZ8EayTGp7UeA_30_258[TM__AZJHBAzoQYZ8EayTGp7UeA_32] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_32+2];
}
TM__AZJHBAzoQYZ8EayTGp7UeA_0[260].len = 258; TM__AZJHBAzoQYZ8EayTGp7UeA_0[260].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[260].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_30_258[0];
NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[260];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[1].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[1].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, kind);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[1].typ = (&NTIcomponent95kind__hDjVFZyz7iZWUbN9bi4D1CA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[1].name = "kind";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[1] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[261];
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.size = sizeof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg);
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.align = NIM_ALIGNOF(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg);
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.kind = 18;
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.base = 0;
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.flags = 3;
TM__AZJHBAzoQYZ8EayTGp7UeA_33_2[0] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[263];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[263].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[263].offset = offsetof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, x);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[263].typ = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[263].name = "x";
TM__AZJHBAzoQYZ8EayTGp7UeA_33_2[1] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[264];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[264].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[264].offset = offsetof(tyObject_point__JrH5NUNRoyvJEz3IQyO9bBg, y);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[264].typ = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[264].name = "y";
TM__AZJHBAzoQYZ8EayTGp7UeA_0[262].len = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[262].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[262].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_33_2[0];
NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[262];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[261].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[261].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, position);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[261].typ = (&NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[261].name = "position";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[2] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[265];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[265].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[265].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, custom_displacement);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[265].typ = (&NTIpoint__JrH5NUNRoyvJEz3IQyO9bBg_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[265].name = "custom_displacement";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[3] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[266];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[266].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[266].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, rotation);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[266].typ = (&NTIuint56__k3HXouOuhqAKq0dx450lXQ_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[266].name = "rotation";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[4] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[267];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[267].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[267].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, real_offset);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[267].typ = (&NTIint56__chXunH2dwinSkhpA6JnsXw_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[267].name = "real_offset";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[5] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[268];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[268].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[268].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, permanent_id);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[268].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[268].name = "permanent_id";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[6] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[269];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[269].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[269].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, custom_string);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[269].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[269].name = "custom_string";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[7] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[270];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[270].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[270].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, custom_id);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[270].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[270].name = "custom_id";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[8] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[271];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[271].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[271].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, setting1);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[271].typ = (&NTIuint5452__wMtfD88jmrPZwfzTH9c8e9cA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[271].name = "setting_1";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[9] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[272];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[272].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[272].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, setting2);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[272].typ = (&NTIuint5452__wMtfD88jmrPZwfzTH9c8e9cA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[272].name = "setting_2";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[10] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[273];
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.size = sizeof(tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA);
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.align = NIM_ALIGNOF(tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA);
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.kind = 18;
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.base = 0;
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.flags = 2;
TM__AZJHBAzoQYZ8EayTGp7UeA_34_2[0] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[275];
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.size = sizeof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g);
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.align = NIM_ALIGNOF(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g);
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.kind = 18;
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.base = 0;
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.flags = 2;
TM__AZJHBAzoQYZ8EayTGp7UeA_35_3[0] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[277];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[277].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[277].offset = offsetof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g, Field0);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[277].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[277].name = "Field0";
TM__AZJHBAzoQYZ8EayTGp7UeA_35_3[1] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[278];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[278].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[278].offset = offsetof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g, Field1);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[278].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[278].name = "Field1";
TM__AZJHBAzoQYZ8EayTGp7UeA_35_3[2] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[279];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[279].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[279].offset = offsetof(tyTuple__kuMQ1fbjJlHtwKTmBGAe6g, Field2);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[279].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[279].name = "Field2";
TM__AZJHBAzoQYZ8EayTGp7UeA_0[276].len = 3; TM__AZJHBAzoQYZ8EayTGp7UeA_0[276].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[276].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_35_3[0];
NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[276];
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.size = sizeof(tySequence__7s5HyddQ0f9bxMNILHrXwJQ*);
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.align = NIM_ALIGNOF(tySequence__7s5HyddQ0f9bxMNILHrXwJQ*);
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.kind = 24;
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.base = (&NTIkeyvaluepair__kuMQ1fbjJlHtwKTmBGAe6g_);
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.flags = 2;
NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_.marker = Marker_tySequence__7s5HyddQ0f9bxMNILHrXwJQ;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[275].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[275].offset = offsetof(tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA, data);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[275].typ = (&NTIkeyvaluepairseq__7s5HyddQ0f9bxMNILHrXwJQ_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[275].name = "data";
TM__AZJHBAzoQYZ8EayTGp7UeA_34_2[1] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[280];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[280].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[280].offset = offsetof(tyObject_Table__N0H9bDibSHG9c6NYdKk0RfmA, counter);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[280].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[280].name = "counter";
TM__AZJHBAzoQYZ8EayTGp7UeA_0[274].len = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[274].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[274].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_34_2[0];
NTItable__N0H9bDibSHG9c6NYdKk0RfmA_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[274];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[273].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[273].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, selected_programs);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[273].typ = (&NTItable__N0H9bDibSHG9c6NYdKk0RfmA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[273].name = "selected_programs";
TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[11] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[281];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[281].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[281].offset = offsetof(tyObject_parse_component__wCcLGue1jmF9be5MVaiBz9aQ, ui_order);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[281].typ = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[281].name = "ui_order";
TM__AZJHBAzoQYZ8EayTGp7UeA_0[0].len = 12; TM__AZJHBAzoQYZ8EayTGp7UeA_0[0].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[0].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_29_12[0];
NTIparse95component__wCcLGue1jmF9be5MVaiBz9aQ_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[0];
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.size = sizeof(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw);
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.align = NIM_ALIGNOF(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw);
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.kind = 18;
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.base = 0;
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.flags = 2;
TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[0] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[283];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[283].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[283].offset = offsetof(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw, path);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[283].typ = (&NTIseqLpointT__XAZNH1jPFL9aAWN7LeA3eng_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[283].name = "path";
TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[1] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[284];
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.size = sizeof(tyEnum_wire_kind__lpUm9cpOexnuxkIZLrG7vjA);
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.align = NIM_ALIGNOF(tyEnum_wire_kind__lpUm9cpOexnuxkIZLrG7vjA);
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.kind = 14;
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.base = 0;
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.flags = 3;
for (TM__AZJHBAzoQYZ8EayTGp7UeA_39 = 0; TM__AZJHBAzoQYZ8EayTGp7UeA_39 < 5; TM__AZJHBAzoQYZ8EayTGp7UeA_39++) {
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_39+285].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_39+285].offset = TM__AZJHBAzoQYZ8EayTGp7UeA_39;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_39+285].name = TM__AZJHBAzoQYZ8EayTGp7UeA_38[TM__AZJHBAzoQYZ8EayTGp7UeA_39];
TM__AZJHBAzoQYZ8EayTGp7UeA_37_5[TM__AZJHBAzoQYZ8EayTGp7UeA_39] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[TM__AZJHBAzoQYZ8EayTGp7UeA_39+285];
}
TM__AZJHBAzoQYZ8EayTGp7UeA_0[290].len = 5; TM__AZJHBAzoQYZ8EayTGp7UeA_0[290].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[290].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_37_5[0];
NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[290];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[284].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[284].offset = offsetof(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw, kind);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[284].typ = (&NTIwire95kind__lpUm9cpOexnuxkIZLrG7vjA_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[284].name = "kind";
TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[2] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[291];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[291].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[291].offset = offsetof(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw, color);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[291].typ = (&NTIuint56__k3HXouOuhqAKq0dx450lXQ_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[291].name = "color";
TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[3] = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[292];
TM__AZJHBAzoQYZ8EayTGp7UeA_0[292].kind = 1;
TM__AZJHBAzoQYZ8EayTGp7UeA_0[292].offset = offsetof(tyObject_parse_wire__lDui4XfQBZ1iej2kOBQebw, comment);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[292].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__AZJHBAzoQYZ8EayTGp7UeA_0[292].name = "comment";
TM__AZJHBAzoQYZ8EayTGp7UeA_0[282].len = 4; TM__AZJHBAzoQYZ8EayTGp7UeA_0[282].kind = 2; TM__AZJHBAzoQYZ8EayTGp7UeA_0[282].sons = &TM__AZJHBAzoQYZ8EayTGp7UeA_36_4[0];
NTIparse95wire__lDui4XfQBZ1iej2kOBQebw_.node = &TM__AZJHBAzoQYZ8EayTGp7UeA_0[282];
}

