/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyTuple__HKalArfYTzTC9bE4LdiUViQ tyTuple__HKalArfYTzTC9bE4LdiUViQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyTuple__HKalArfYTzTC9bE4LdiUViQ {
NU32 Field0;
NI Field1;
};
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s_p0, NI newLen_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__HKalArfYTzTC9bE4LdiUViQ, varint__librariesZsupersnappyZsupersnappyZcommon_u79)(NimStringDesc* buf_p0) {
	tyTuple__HKalArfYTzTC9bE4LdiUViQ result;
	NU8 b;
	NU32 colontmp__9;
	NI colontmp__10;
{	nimZeroMem((void*)(&result), sizeof(tyTuple__HKalArfYTzTC9bE4LdiUViQ));
	{
		if (!((buf_p0 ? buf_p0->Sup.len : 0) == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	b = ((NU8) (((NU8)(buf_p0->data[((NI)0)]))));
	result.Field0 = ((NU32) ((NU8)(b & ((NU8)127))));
	result.Field1 = ((NI)1);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA7_;
		goto BeforeRet_;
	}
LA7_: ;
	{
		NU32 colontmp_;
		NI colontmp__2;
		if (!((buf_p0 ? buf_p0->Sup.len : 0) == ((NI)1))) goto LA11_;
		colontmp_ = ((NU32)0);
		colontmp__2 = ((NI)0);
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA11_: ;
	b = ((NU8) (((NU8)(buf_p0->data[((NI)1)]))));
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)7))));
	result.Field1 = ((NI)2);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA15_;
		goto BeforeRet_;
	}
LA15_: ;
	{
		NU32 colontmp__3;
		NI colontmp__4;
		if (!((buf_p0 ? buf_p0->Sup.len : 0) == ((NI)2))) goto LA19_;
		colontmp__3 = ((NU32)0);
		colontmp__4 = ((NI)0);
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA19_: ;
	b = ((NU8) (((NU8)(buf_p0->data[((NI)2)]))));
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)14))));
	result.Field1 = ((NI)3);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA23_;
		goto BeforeRet_;
	}
LA23_: ;
	{
		NU32 colontmp__5;
		NI colontmp__6;
		if (!((buf_p0 ? buf_p0->Sup.len : 0) == ((NI)3))) goto LA27_;
		colontmp__5 = ((NU32)0);
		colontmp__6 = ((NI)0);
		result.Field0 = colontmp__5;
		result.Field1 = colontmp__6;
		goto BeforeRet_;
	}
LA27_: ;
	b = ((NU8) (((NU8)(buf_p0->data[((NI)3)]))));
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)21))));
	result.Field1 = ((NI)4);
	{
		if (!((NU8)(b) < (NU8)(((NU8)128)))) goto LA31_;
		goto BeforeRet_;
	}
LA31_: ;
	{
		NU32 colontmp__7;
		NI colontmp__8;
		if (!((buf_p0 ? buf_p0->Sup.len : 0) == ((NI)4))) goto LA35_;
		colontmp__7 = ((NU32)0);
		colontmp__8 = ((NI)0);
		result.Field0 = colontmp__7;
		result.Field1 = colontmp__8;
		goto BeforeRet_;
	}
LA35_: ;
	b = ((NU8) (((NU8)(buf_p0->data[((NI)4)]))));
	result.Field0 = (NU32)(result.Field0 | (NU32)((NU64)(((NU32) ((NU8)(b & ((NU8)127))))) << (NU64)(((NI)28))));
	result.Field1 = ((NI)5);
	{
		if (!((NU8)(b) < (NU8)(((NU8)16)))) goto LA39_;
		goto BeforeRet_;
	}
LA39_: ;
	colontmp__9 = ((NU32)0);
	colontmp__10 = ((NI)0);
	result.Field0 = colontmp__9;
	result.Field1 = colontmp__10;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, varint__librariesZsupersnappyZsupersnappyZcommon_u20)(NU32 value_p0) {
	NimStringDesc* result;
	result = NIM_NIL;
	{
		if (!((NU32)(value_p0) < (NU32)(((NU32)128)))) goto LA3_;
		result = setLengthStr(result, ((NI)1));
		result->data[((NI)0)] = ((NIM_CHAR) (value_p0));
	}
	goto LA1_;
LA3_: ;
	{
		if (!((NU32)(value_p0) < (NU32)(((NU32)16384)))) goto LA6_;
		result = setLengthStr(result, ((NI)2));
		result->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) & ((NU32)255))));
	}
	goto LA1_;
LA6_: ;
	{
		if (!((NU32)(value_p0) < (NU32)(((NU32)2097152)))) goto LA9_;
		result = setLengthStr(result, ((NI)3));
		result->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) & ((NU32)255))));
	}
	goto LA1_;
LA9_: ;
	{
		if (!((NU32)(value_p0) < (NU32)(((NU32)268435456)))) goto LA12_;
		result = setLengthStr(result, ((NI)4));
		result->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)3)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) & ((NU32)255))));
	}
	goto LA1_;
LA12_: ;
	{
		result = setLengthStr(result, ((NI)5));
		result->data[((NI)0)] = ((NIM_CHAR) ((NU32)((NU32)(value_p0 | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)1)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)7))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)2)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)14))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)3)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)21))) | ((NU32)128)) & ((NU32)255))));
		result->data[((NI)4)] = ((NIM_CHAR) ((NU32)((NU32)((NU32)(value_p0) >> (NU64)(((NI)28))) & ((NU32)255))));
	}
LA1_: ;
	return result;
}
