/* Generated by Nim Compiler v2.0.0 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <windows.h>
#include <string.h>
#include <intrin.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple__HKalArfYTzTC9bE4LdiUViQ tyTuple__HKalArfYTzTC9bE4LdiUViQ;
typedef struct tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig;
typedef struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g;
typedef struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw tySequence__2ALwPJKv8Nz8mMm4Hy9crdw;
typedef struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ;
typedef struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w;
typedef struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA;
typedef struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg;
typedef struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg;
typedef struct tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ;
typedef struct tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg;
typedef struct tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw;
typedef struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw;
typedef struct tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw;
typedef struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ;
typedef struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw;
typedef struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyTuple__yGsE49aVStLN4u9aOPDn3wgA;
typedef struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig;
typedef struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew;
typedef struct tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A;
typedef struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw;
typedef struct tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg;
typedef struct tySequence__uFLLGQVsiasALrzzzvqnZw tySequence__uFLLGQVsiasALrzzzvqnZw;
typedef struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA;
struct TGenericSeq {
	NI len;
	NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple__HKalArfYTzTC9bE4LdiUViQ {
NU32 Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ;
typedef NU8 tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p_p0, NI op_p1);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p_p0);
struct TNimType {
	NI size;
	NI align;
	tyEnum_TNimKind__gvi1epwSO1OTm5TYYpvciQ kind;
	tySet_tyEnum_TNimTypeFlag__kg8CbOmSm78f9cYZNYwXtRw flags;
	TNimType* base;
	TNimNode* node;
	void* finalizer;
	tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
	tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringDesc* message;
	tySequence__2ALwPJKv8Nz8mMm4Hy9crdw* trace;
	Exception* up;
};
struct tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg {
  Exception Sup;
};
struct tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g {
  tyObject_CatchableError__plmui9cLQDf1IsFzhQAAHyg Sup;
};
struct tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig {
  tyObject_ValueError__I29b1dwcLrTw15fJ82YvM2g Sup;
};
typedef NU8 tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g;
struct TNimNode {
	tyEnum_TNimNodeKind__27ptuqE7C12XXCcK2N0u8g kind;
	NI offset;
	TNimType* typ;
	NCSTRING name;
	NI len;
	TNimNode** sons;
};
struct tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ {
	NI refcount;
	TNimType* typ;
};
struct tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg {
	void* bottom;
};
struct tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w {
	NI len;
	NI cap;
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ** d;
};
typedef tyObject_SmallChunk__w9a0u4dQu8DmP9ar7taA9a1KQ* tyArray__n7mWiyIukhFBx9aT5LAe9aJA[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A[32];
typedef tyArray__WGXn9bPkVO5o9b7NyJ5gKs0A tyArray__KmV84pECaCWWb69bu0P29bMw[24];
typedef tyObject_Trunk__gVwES7cDN6Q2RP9aWdpqG9cw* tyArray__giUOXU0N3dRSsrZfIxZ64w[256];
struct tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw {
	tyArray__giUOXU0N3dRSsrZfIxZ64w data;
};
typedef tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* tyArray__q2FnL9bDEMyzH1CwZ2zDygA[2];
struct tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ {
	tyArray__q2FnL9bDEMyzH1CwZ2zDygA link;
	NI key;
	NI upperBound;
	NI level;
};
struct tyTuple__yGsE49aVStLN4u9aOPDn3wgA {
tyObject_BigChunk__okXMy7XYtzcsoqFE9bRwBYg* Field0;
NI Field1;
};
typedef tyTuple__yGsE49aVStLN4u9aOPDn3wgA tyArray__mQIPGEktuAkOvmbQBXhmIA[30];
struct tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw {
	NI len;
	tyArray__mQIPGEktuAkOvmbQBXhmIA chunks;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw* next;
};
struct tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg {
	NI minLargeObj;
	NI maxLargeObj;
	tyArray__n7mWiyIukhFBx9aT5LAe9aJA freeSmallChunks;
	NU32 flBitmap;
	tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
	tyArray__KmV84pECaCWWb69bu0P29bMw matrix;
	tyObject_LLChunk__79cXIjTFIUqNFx5h5T7FaUw* llmem;
	NI currMem;
	NI maxMem;
	NI freeMem;
	NI occ;
	NI lastSize;
	tyObject_IntSet__Hj9a1ruHjmf5pKk3Cn1vxfw chunkStarts;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* root;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* deleted;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* last;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ* freeAvlNodes;
	NIM_BOOL lockActive;
	NIM_BOOL locked;
	NIM_BOOL blockChunkSizeIncrease;
	NI nextChunkSize;
	tyObject_AvlNode__Qbw4KGIHRpEXYKQafqDDzQ bottomData;
	tyObject_HeapLinks__CbSHuTiYQRpQS6rnRQqLXw heapLinks;
};
struct tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig {
	NI stackScans;
	NI cycleCollections;
	NI maxThreshold;
	NI maxStackSize;
	NI maxStackCells;
	NI cycleTableSize;
	NI64 maxPause;
};
struct tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew {
	NI counter;
	NI max;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A* head;
	tyObject_PageDesc__sTjx34J2V9bVnrAB9cQYHV4A** data;
};
struct tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw {
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* head;
	tyObject_SharedListNodecolonObjectType___Z0OFQ3dU20KNgfzV0pjQtg* tail;
	CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA {
	tyObject_GcStack__kd79bxm63Cm3Vo6Y1pBZOSg stack;
	NI cycleThreshold;
	NI zctThreshold;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w zct;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w decStack;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w tempStack;
	NI recGcLock;
	tyObject_MemRegion__ZGZbIiPzVQl4g2OpfLjncg region;
	tyObject_GcStat__XV9cHyZLE5ykPsA9bb23ixig stat;
	tyObject_CellSet__qzG2Wr8EKyzZ9aM6n3kdGew marked;
	tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w additionalRoots;
	tyObject_SharedList__g4j7x1L9ci2QA5L1stmlexw toDispose;
	NI gcThreadId;
};
typedef NU32 tyArray__xsE8WL1yT5DKfrMdYB89bYA[5];
typedef NU16 tyArray__xfVMZRB2nlyn9aJsrwM5Jqg[256];
struct tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__uFLLGQVsiasALrzzzvqnZw {
  TGenericSeq Sup;
  NU16 data[SEQ_DECL_SIZE];
};
struct tySequence__2ALwPJKv8Nz8mMm4Hy9crdw {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__nOjYJiLBbFH64nNmW1UArA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple__HKalArfYTzTC9bE4LdiUViQ, varint__librariesZsupersnappyZsupersnappyZcommon_u79)(NimStringDesc* buf_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d_p0, NI op_p1);
static N_NIMCALL(void, Marker_tyRef__wWUu09bEDZScs6vMXWBt3uQ)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ_p0, NI size_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src_p0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0);
static N_INLINE(void, decRef__system_u6034)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1);
static N_INLINE(void, rtlAddZCT__system_u6032)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_u5983)(tyObject_CellSeq__KtUV2STwH1uCukBriA7b3w* s_p0, tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p1);
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u5989)(void* usr_p0);
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, incRef__system_u6027)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0);
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest_p0, void* src_p1);
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, varint__librariesZsupersnappyZsupersnappyZcommon_u20)(NU32 value_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__uFLLGQVsiasALrzzzvqnZw*, newSeq__librariesZsupersnappyZsupersnappy_u1112)(NI len_p0);
static N_NIMCALL(void, Marker_tySequence__uFLLGQVsiasALrzzzvqnZw)(void* p, NI op);
static N_INLINE(NU, min__librariesZsupersnappyZsupersnappy_u1138)(NU x_p0, NU y_p1);
N_LIB_PRIVATE N_NIMCALL(void, compressFragment__librariesZsupersnappyZsupersnappy_u861)(NimStringDesc** dst_p0, NimStringDesc* src_p1, NU* op_p2, NU start_p3, NU len_p4, tySequence__uFLLGQVsiasALrzzzvqnZw** compressTable_p5);
static N_INLINE(void, zeroMem__system_u1756)(void* p_p0, NI size_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, emitLiteral__librariesZsupersnappyZsupersnappy_u498)(NimStringDesc** dst_p0, NimStringDesc* src_p1, NU* op_p2, NU ip_p3, NU len_p4, NIM_BOOL fastPath_p5);
static N_INLINE(NU, findMatchLength__librariesZsupersnappyZsupersnappy_u648)(NimStringDesc* src_p0, NU s1_p1, NU s2_p2, NU limit_p3);
static N_INLINE(NI, countTrailingZeroBits__librariesZsupersnappyZsupersnappy_u727)(NU64 x_p0);
static N_INLINE(NI, firstSetBit__librariesZsupersnappyZsupersnappy_u733)(NU64 x_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, emitCopy__librariesZsupersnappyZsupersnappy_u847)(NimStringDesc** dst_p0, NU* op_p1, NU offset_p2, NU len_p3);
N_LIB_PRIVATE N_NIMCALL(void, emitCopy64Max__librariesZsupersnappyZsupersnappy_u798)(NimStringDesc** dst_p0, NU* op_p1, NU offset_p2, NU len_p3);
extern TNimType NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_;
N_LIB_PRIVATE TNimType NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_;
N_LIB_PRIVATE TNimType NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_;
STRING_LITERAL(TM__PlnUgi9cchxmhqZzbwsLzzA_2, "Invalid buffer, unable to uncompress", 36);
STRING_LITERAL(TM__PlnUgi9cchxmhqZzbwsLzzA_3, "Unable to compress buffer", 25);
extern TNimType NTIuint4954__M4na42GvebBMnI5wV9cYMxg_;
N_LIB_PRIVATE TNimType NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_;
N_LIB_PRIVATE NIM_CONST tyArray__xsE8WL1yT5DKfrMdYB89bYA lenWordMask__librariesZsupersnappyZsupersnappy_u4 = {((NU32)0),
((NU32)255),
((NU32)65535),
((NU32)16777215),
((NU32)IL64(4294967295))}
;
N_LIB_PRIVATE NIM_CONST tyArray__xfVMZRB2nlyn9aJsrwM5Jqg uncompressLookup__librariesZsupersnappyZsupersnappy_u3 = {((NU16)1),
((NU16)2052),
((NU16)4097),
((NU16)8193),
((NU16)2),
((NU16)2053),
((NU16)4098),
((NU16)8194),
((NU16)3),
((NU16)2054),
((NU16)4099),
((NU16)8195),
((NU16)4),
((NU16)2055),
((NU16)4100),
((NU16)8196),
((NU16)5),
((NU16)2056),
((NU16)4101),
((NU16)8197),
((NU16)6),
((NU16)2057),
((NU16)4102),
((NU16)8198),
((NU16)7),
((NU16)2058),
((NU16)4103),
((NU16)8199),
((NU16)8),
((NU16)2059),
((NU16)4104),
((NU16)8200),
((NU16)9),
((NU16)2308),
((NU16)4105),
((NU16)8201),
((NU16)10),
((NU16)2309),
((NU16)4106),
((NU16)8202),
((NU16)11),
((NU16)2310),
((NU16)4107),
((NU16)8203),
((NU16)12),
((NU16)2311),
((NU16)4108),
((NU16)8204),
((NU16)13),
((NU16)2312),
((NU16)4109),
((NU16)8205),
((NU16)14),
((NU16)2313),
((NU16)4110),
((NU16)8206),
((NU16)15),
((NU16)2314),
((NU16)4111),
((NU16)8207),
((NU16)16),
((NU16)2315),
((NU16)4112),
((NU16)8208),
((NU16)17),
((NU16)2564),
((NU16)4113),
((NU16)8209),
((NU16)18),
((NU16)2565),
((NU16)4114),
((NU16)8210),
((NU16)19),
((NU16)2566),
((NU16)4115),
((NU16)8211),
((NU16)20),
((NU16)2567),
((NU16)4116),
((NU16)8212),
((NU16)21),
((NU16)2568),
((NU16)4117),
((NU16)8213),
((NU16)22),
((NU16)2569),
((NU16)4118),
((NU16)8214),
((NU16)23),
((NU16)2570),
((NU16)4119),
((NU16)8215),
((NU16)24),
((NU16)2571),
((NU16)4120),
((NU16)8216),
((NU16)25),
((NU16)2820),
((NU16)4121),
((NU16)8217),
((NU16)26),
((NU16)2821),
((NU16)4122),
((NU16)8218),
((NU16)27),
((NU16)2822),
((NU16)4123),
((NU16)8219),
((NU16)28),
((NU16)2823),
((NU16)4124),
((NU16)8220),
((NU16)29),
((NU16)2824),
((NU16)4125),
((NU16)8221),
((NU16)30),
((NU16)2825),
((NU16)4126),
((NU16)8222),
((NU16)31),
((NU16)2826),
((NU16)4127),
((NU16)8223),
((NU16)32),
((NU16)2827),
((NU16)4128),
((NU16)8224),
((NU16)33),
((NU16)3076),
((NU16)4129),
((NU16)8225),
((NU16)34),
((NU16)3077),
((NU16)4130),
((NU16)8226),
((NU16)35),
((NU16)3078),
((NU16)4131),
((NU16)8227),
((NU16)36),
((NU16)3079),
((NU16)4132),
((NU16)8228),
((NU16)37),
((NU16)3080),
((NU16)4133),
((NU16)8229),
((NU16)38),
((NU16)3081),
((NU16)4134),
((NU16)8230),
((NU16)39),
((NU16)3082),
((NU16)4135),
((NU16)8231),
((NU16)40),
((NU16)3083),
((NU16)4136),
((NU16)8232),
((NU16)41),
((NU16)3332),
((NU16)4137),
((NU16)8233),
((NU16)42),
((NU16)3333),
((NU16)4138),
((NU16)8234),
((NU16)43),
((NU16)3334),
((NU16)4139),
((NU16)8235),
((NU16)44),
((NU16)3335),
((NU16)4140),
((NU16)8236),
((NU16)45),
((NU16)3336),
((NU16)4141),
((NU16)8237),
((NU16)46),
((NU16)3337),
((NU16)4142),
((NU16)8238),
((NU16)47),
((NU16)3338),
((NU16)4143),
((NU16)8239),
((NU16)48),
((NU16)3339),
((NU16)4144),
((NU16)8240),
((NU16)49),
((NU16)3588),
((NU16)4145),
((NU16)8241),
((NU16)50),
((NU16)3589),
((NU16)4146),
((NU16)8242),
((NU16)51),
((NU16)3590),
((NU16)4147),
((NU16)8243),
((NU16)52),
((NU16)3591),
((NU16)4148),
((NU16)8244),
((NU16)53),
((NU16)3592),
((NU16)4149),
((NU16)8245),
((NU16)54),
((NU16)3593),
((NU16)4150),
((NU16)8246),
((NU16)55),
((NU16)3594),
((NU16)4151),
((NU16)8247),
((NU16)56),
((NU16)3595),
((NU16)4152),
((NU16)8248),
((NU16)57),
((NU16)3844),
((NU16)4153),
((NU16)8249),
((NU16)58),
((NU16)3845),
((NU16)4154),
((NU16)8250),
((NU16)59),
((NU16)3846),
((NU16)4155),
((NU16)8251),
((NU16)60),
((NU16)3847),
((NU16)4156),
((NU16)8252),
((NU16)2049),
((NU16)3848),
((NU16)4157),
((NU16)8253),
((NU16)4097),
((NU16)3849),
((NU16)4158),
((NU16)8254),
((NU16)6145),
((NU16)3850),
((NU16)4159),
((NU16)8255),
((NU16)8193),
((NU16)3851),
((NU16)4160),
((NU16)8256)}
;
extern NIM_THREADVAR tyObject_GcHeap__p9coMTwtTxWiVyf2LmDtNlA gch__system_u5922;
static N_NIMCALL(void, Marker_tyRef__wWUu09bEDZScs6vMXWBt3uQ)(void* p, NI op) {
	tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* a;
	a = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
static N_INLINE(NI, minuspercent___system_u806)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_u1083)(NI x_p0, NI y_p1) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x_p0))) < (NU64)(((NU) (y_p1))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_u6032)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	addZCT__system_u5983((&gch__system_u5922.zct), c_p0);
}
static N_INLINE(void, decRef__system_u6034)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = minuspercent___system_u806((*c_p0).refcount, ((NI)8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_u1083((*c_p0).refcount, ((NI)8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_u6032(c_p0);
	}
LA4_: ;
}
static N_INLINE(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*, usrToCell__system_u5989)(void* usr_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* result;
	NI T1_;
	result = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u806(((NI) (ptrdiff_t) (usr_p0)), ((NI)16));
	result = ((tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p_p0) {
	tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T1_;
	T1_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
	T1_ = usrToCell__system_u5989(p_p0);
	decRef__system_u6034(T1_);
}
static N_INLINE(NI, pluspercent___system_u786)(NI x_p0, NI y_p1) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, incRef__system_u6027)(tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* c_p0) {
	(*c_p0).refcount = pluspercent___system_u786((*c_p0).refcount, ((NI)8));
}
static N_INLINE(void, asgnRef)(void** dest_p0, void* src_p1) {
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T5_;
		if (!!((src_p1 == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T5_ = usrToCell__system_u5989(src_p1);
		incRef__system_u6027(T5_);
	}
LA3_: ;
	{
		tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ* T10_;
		if (!!(((*dest_p0) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__AMJ4VsIqEE6vg6u4IKnsAQ*)0;
		T10_ = usrToCell__system_u5989((*dest_p0));
		decRef__system_u6034(T10_);
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1759)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(void, uncompress__librariesZsupersnappyZsupersnappy_u18)(NimStringDesc** dst_p0, NimStringDesc* src_p1) {
	tyTuple__HKalArfYTzTC9bE4LdiUViQ tmpTuple;
	NU32 uncompressedLen;
	NI bytesRead;
	NU srcLen;
	NU dstLen;
	NU ip;
	NU op;
	tmpTuple = varint__librariesZsupersnappyZsupersnappyZcommon_u79(src_p1);
	uncompressedLen = tmpTuple.Field0;
	bytesRead = tmpTuple.Field1;
	{
		tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T5_;
		NimStringDesc* T6_;
		if (!(bytesRead <= ((NI)0))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
		(*T5_).Sup.Sup.Sup.name = "SnappyError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.Sup.message; (*T5_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_2));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "SnappyError", "uncompress", "supersnappy.nim", 68);
	}
LA3_: ;
	unsureAsgnRef((void**) (&(*dst_p0)), setLengthStr((*dst_p0), ((NI) (uncompressedLen))));
	srcLen = ((NU) ((src_p1 ? src_p1->Sup.len : 0)));
	dstLen = ((NU) (((*dst_p0) ? (*dst_p0)->Sup.len : 0)));
	ip = ((NU) (bytesRead));
	op = ((NU)0);
	{
		while (1) {
			if (!((NU64)(ip) < (NU64)(srcLen))) goto LA8;
			{
				NU len;
				if (!((NU8)(((NU8) (((NU8)(src_p1->data[ip])))) & ((NU8)3)) == ((NU8)0))) goto LA11_;
				len = (NU)((NU64)((NU)((NU64)(((NU) (((NU8)(src_p1->data[ip]))))) >> (NU64)(((NI)2)))) + (NU64)(((NU)1)));
				ip += ((NI)1);
				{
					NIM_BOOL T15_;
					NIM_BOOL T16_;
					T15_ = (NIM_BOOL)0;
					T16_ = (NIM_BOOL)0;
					T16_ = ((NU64)(len) <= (NU64)(((NU)16)));
					if (!(T16_)) goto LA17_;
					T16_ = ((NU64)((NU)((NU64)(ip) + (NU64)(((NU)16)))) < (NU64)(srcLen));
LA17_: ;
					T15_ = T16_;
					if (!(T15_)) goto LA18_;
					T15_ = ((NU64)((NU)((NU64)(op) + (NU64)(((NU)16)))) < (NU64)(dstLen));
LA18_: ;
					if (!T15_) goto LA19_;
					(*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)(op) + (NU64)(((NU)0)))])))) = (*((NU64*) ((&src_p1->data[(NU)((NU64)(ip) + (NU64)(((NU)0)))]))));
					(*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)(op) + (NU64)(((NU)8)))])))) = (*((NU64*) ((&src_p1->data[(NU)((NU64)(ip) + (NU64)(((NU)8)))]))));
				}
				goto LA13_;
LA19_: ;
				{
					{
						NU bytes;
						if (!((NU64)(((NU)61)) <= (NU64)(len))) goto LA24_;
						bytes = (NU)((NU64)(len) - (NU64)(((NU)60)));
						len = ((NU) ((NU32)((NU32)((NU32)((*((NU32*) ((&src_p1->data[ip])))) & lenWordMask__librariesZsupersnappyZsupersnappy_u4[(bytes)- 0])) + (NU32)(((NU32)1)))));
						ip += bytes;
					}
LA24_: ;
					{
						NIM_BOOL T28_;
						NIM_BOOL T29_;
						tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T34_;
						NimStringDesc* T35_;
						T28_ = (NIM_BOOL)0;
						T29_ = (NIM_BOOL)0;
						T29_ = ((NU64)(len) <= (NU64)(((NU)0)));
						if (T29_) goto LA30_;
						T29_ = ((NU64)(srcLen) < (NU64)((NU)((NU64)(ip) + (NU64)(len))));
LA30_: ;
						T28_ = T29_;
						if (T28_) goto LA31_;
						T28_ = ((NU64)(dstLen) < (NU64)((NU)((NU64)(op) + (NU64)(len))));
LA31_: ;
						if (!T28_) goto LA32_;
						T34_ = NIM_NIL;
						T34_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
						(*T34_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
						(*T34_).Sup.Sup.Sup.name = "SnappyError";
						T35_ = NIM_NIL;
						T35_ = (*T34_).Sup.Sup.Sup.message; (*T34_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_2));
						if (T35_) nimGCunrefNoCycle(T35_);
						asgnRef((void**) (&(*T34_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
						raiseExceptionEx((Exception*)T34_, "SnappyError", "uncompress", "supersnappy.nim", 93);
					}
LA32_: ;
					copyMem__system_u1759(((void*) ((&(*dst_p0)->data[op]))), ((void*) ((&src_p1->data[ip]))), ((NI) (len)));
				}
LA13_: ;
				ip += len;
				op += len;
			}
			goto LA9_;
LA11_: ;
			{
				NU entry;
				NU32 trailer;
				NU len_2;
				NU offset;
				{
					tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T41_;
					NimStringDesc* T42_;
					if (!((NU64)(srcLen) <= (NU64)((NU)((NU64)(ip) + (NU64)(((NU)1)))))) goto LA39_;
					T41_ = NIM_NIL;
					T41_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
					(*T41_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
					(*T41_).Sup.Sup.Sup.name = "SnappyError";
					T42_ = NIM_NIL;
					T42_ = (*T41_).Sup.Sup.Sup.message; (*T41_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_2));
					if (T42_) nimGCunrefNoCycle(T42_);
					asgnRef((void**) (&(*T41_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T41_, "SnappyError", "uncompress", "supersnappy.nim", 101);
				}
LA39_: ;
				entry = ((NU) (uncompressLookup__librariesZsupersnappyZsupersnappy_u3[(((NU8) (((NU8)(src_p1->data[ip])))))- 0]));
				trailer = (NU32)((*((NU32*) ((&src_p1->data[(NU)((NU64)(ip) + (NU64)(((NU)1)))])))) & lenWordMask__librariesZsupersnappyZsupersnappy_u4[((NU)((NU64)(entry) >> (NU64)(((NI)11))))- 0]);
				len_2 = (NU)(entry & ((NU)255));
				offset = (NU)((NU64)((NU)(entry & ((NU)1792))) + (NU64)(((NU) (trailer))));
				ip += (NU)((NU64)((NU)((NU64)(entry) >> (NU64)(((NI)11)))) + (NU64)(((NU)1)));
				{
					NIM_BOOL T45_;
					tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T49_;
					NimStringDesc* T50_;
					T45_ = (NIM_BOOL)0;
					T45_ = ((NU64)((NU)((NU64)(dstLen) - (NU64)(op))) < (NU64)(len_2));
					if (T45_) goto LA46_;
					T45_ = ((NU64)(op) <= (NU64)((NU)((NU64)(offset) - (NU64)(((NU)1)))));
LA46_: ;
					if (!T45_) goto LA47_;
					T49_ = NIM_NIL;
					T49_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
					(*T49_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
					(*T49_).Sup.Sup.Sup.name = "SnappyError";
					T50_ = NIM_NIL;
					T50_ = (*T49_).Sup.Sup.Sup.message; (*T49_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_2));
					if (T50_) nimGCunrefNoCycle(T50_);
					asgnRef((void**) (&(*T49_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T49_, "SnappyError", "uncompress", "supersnappy.nim", 112);
				}
LA47_: ;
				{
					NIM_BOOL T53_;
					NIM_BOOL T54_;
					T53_ = (NIM_BOOL)0;
					T54_ = (NIM_BOOL)0;
					T54_ = ((NU64)(len_2) <= (NU64)(((NU)16)));
					if (!(T54_)) goto LA55_;
					T54_ = ((NU64)(((NU)8)) <= (NU64)(offset));
LA55_: ;
					T53_ = T54_;
					if (!(T53_)) goto LA56_;
					T53_ = ((NU64)((NU)((NU64)(op) + (NU64)(((NU)16)))) < (NU64)(dstLen));
LA56_: ;
					if (!T53_) goto LA57_;
					(*((NU64*) ((&(*dst_p0)->data[op])))) = (*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)(op) - (NU64)(offset))]))));
					(*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)(op) + (NU64)(((NU)8)))])))) = (*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)((NU)((NU64)(op) - (NU64)(offset))) + (NU64)(((NU)8)))]))));
					op += len_2;
				}
				goto LA51_;
LA57_: ;
				{
					NU src_2;
					NU pos;
					NI remaining;
					if (!((NU64)((NU)((NU64)(len_2) + (NU64)(((NU)10)))) <= (NU64)((NU)((NU64)(dstLen) - (NU64)(op))))) goto LA60_;
					src_2 = (NU)((NU64)(op) - (NU64)(offset));
					pos = op;
					remaining = ((NI) (len_2));
					{
						while (1) {
							if (!((NU64)((NU)((NU64)(pos) - (NU64)(src_2))) < (NU64)(((NU)8)))) goto LA63;
							(*((NU64*) ((&(*dst_p0)->data[pos])))) = (*((NU64*) ((&(*dst_p0)->data[src_2]))));
							remaining -= ((NI) ((NU)((NU64)(pos) - (NU64)(src_2))));
							pos += (NU)((NU64)(pos) - (NU64)(src_2));
						} LA63: ;
					}
					{
						while (1) {
							if (!(((NI)0) < remaining)) goto LA65;
							(*((NU64*) ((&(*dst_p0)->data[pos])))) = (*((NU64*) ((&(*dst_p0)->data[src_2]))));
							src_2 += ((NI)8);
							pos += ((NI)8);
							remaining -= ((NI)8);
						} LA65: ;
					}
					op += len_2;
				}
				goto LA51_;
LA60_: ;
				{
					{
						NU i;
						NU colontmp_;
						NU i_2;
						i = (NU)0;
						colontmp_ = (NU)0;
						colontmp_ = (NU)((NU64)(op) + (NU64)(len_2));
						i_2 = op;
						{
							while (1) {
								if (!((NU64)(i_2) < (NU64)(colontmp_))) goto LA69;
								i = i_2;
								(*dst_p0)->data[op] = (*dst_p0)->data[(NU)((NU64)(op) - (NU64)(offset))];
								op += ((NI)1);
								i_2 += ((NI)1);
							} LA69: ;
						}
					}
				}
LA51_: ;
			}
LA9_: ;
		} LA8: ;
	}
	{
		tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T74_;
		NimStringDesc* T75_;
		if (!!((op == dstLen))) goto LA72_;
		T74_ = NIM_NIL;
		T74_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
		(*T74_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
		(*T74_).Sup.Sup.Sup.name = "SnappyError";
		T75_ = NIM_NIL;
		T75_ = (*T74_).Sup.Sup.Sup.message; (*T74_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_2));
		if (T75_) nimGCunrefNoCycle(T75_);
		asgnRef((void**) (&(*T74_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T74_, "SnappyError", "uncompress", "supersnappy.nim", 139);
	}
LA72_: ;
}
static N_NIMCALL(void, Marker_tySequence__uFLLGQVsiasALrzzzvqnZw)(void* p, NI op) {
	tySequence__uFLLGQVsiasALrzzzvqnZw* a;
	NI T1_;
	a = (tySequence__uFLLGQVsiasALrzzzvqnZw*)p;
	T1_ = (NI)0;
}
static N_INLINE(NU, min__librariesZsupersnappyZsupersnappy_u1138)(NU x_p0, NU y_p1) {
	NU result;
	result = (NU)0;
	{
		if (!((NU64)(x_p0) <= (NU64)(y_p1))) goto LA3_;
		result = x_p0;
	}
	goto LA1_;
LA3_: ;
	{
		result = y_p1;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, zeroMem__system_u1756)(void* p_p0, NI size_p1) {
	nimZeroMem(p_p0, size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, emitLiteral__librariesZsupersnappyZsupersnappy_u498)(NimStringDesc** dst_p0, NimStringDesc* src_p1, NU* op_p2, NU ip_p3, NU len_p4, NIM_BOOL fastPath_p5) {
	NU n;
{	n = (NU)((NU64)(len_p4) - (NU64)(((NU)1)));
	{
		if (!((NU64)(n) < (NU64)(((NU)60)))) goto LA3_;
		(*dst_p0)->data[(*op_p2)] = ((NIM_CHAR) ((NU)((NU64)(n) << (NU64)(((NI)2)))));
		(*op_p2) += ((NI)1);
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = fastPath_p5;
			if (!(T7_)) goto LA8_;
			T7_ = ((NU64)(len_p4) <= (NU64)(((NU)16)));
LA8_: ;
			if (!T7_) goto LA9_;
			(*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)((*op_p2)) + (NU64)(((NU)0)))])))) = (*((NU64*) ((&src_p1->data[(NU)((NU64)(ip_p3) + (NU64)(((NU)0)))]))));
			(*((NU64*) ((&(*dst_p0)->data[(NU)((NU64)((*op_p2)) + (NU64)(((NU)8)))])))) = (*((NU64*) ((&src_p1->data[(NU)((NU64)(ip_p3) + (NU64)(((NU)8)))]))));
			(*op_p2) += len_p4;
			goto BeforeRet_;
		}
LA9_: ;
	}
	goto LA1_;
LA3_: ;
	{
		NU base;
		NU count;
		base = (*op_p2);
		count = (NU)0;
		(*op_p2) += ((NI)1);
		{
			while (1) {
				if (!((NU64)(((NU)0)) < (NU64)(n))) goto LA13;
				(*dst_p0)->data[(*op_p2)] = ((NIM_CHAR) ((NU)(n & ((NU)255))));
				n = (NU)((NU64)(n) >> (NU64)(((NI)8)));
				(*op_p2) += ((NI)1);
				count += ((NI)1);
			} LA13: ;
		}
		(*dst_p0)->data[base] = ((NIM_CHAR) ((NU)((NU64)((NU)((NU64)(((NU)59)) + (NU64)(count))) << (NU64)(((NI)2)))));
	}
LA1_: ;
	copyMem__system_u1759(((void*) ((&(*dst_p0)->data[(*op_p2)]))), ((void*) ((&src_p1->data[ip_p3]))), ((NI) (len_p4)));
	(*op_p2) += len_p4;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, firstSetBit__librariesZsupersnappyZsupersnappy_u733)(NU64 x_p0) {
	NI result;
	NU64 x_2;
	unsigned long indexX60gensym35_;
	NU8 T1_;
	NI TM__PlnUgi9cchxmhqZzbwsLzzA_4;
	result = (NI)0;
	x_2 = x_p0;
	indexX60gensym35_ = (unsigned long)0;
	T1_ = (NU8)0;
	T1_ = _BitScanForward64((&indexX60gensym35_), x_2);
	(void)(T1_);
	if (nimAddInt(((NI)1), ((NI) (indexX60gensym35_)), &TM__PlnUgi9cchxmhqZzbwsLzzA_4)) { raiseOverflow(); 	};
	result = (NI)(TM__PlnUgi9cchxmhqZzbwsLzzA_4);
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, countTrailingZeroBits__librariesZsupersnappyZsupersnappy_u727)(NU64 x_p0) {
	NI result;
	NU64 x_2;
	NI T1_;
	NI TM__PlnUgi9cchxmhqZzbwsLzzA_5;
	result = (NI)0;
	x_2 = x_p0;
	T1_ = (NI)0;
	T1_ = firstSetBit__librariesZsupersnappyZsupersnappy_u733(x_2);
	if (nimSubInt(T1_, ((NI)1), &TM__PlnUgi9cchxmhqZzbwsLzzA_5)) { raiseOverflow(); 	};
	result = (NI)(TM__PlnUgi9cchxmhqZzbwsLzzA_5);
	return result;
}
static N_INLINE(NU, findMatchLength__librariesZsupersnappyZsupersnappy_u648)(NimStringDesc* src_p0, NU s1_p1, NU s2_p2, NU limit_p3) {
	NU result;
	NU s1_2;
	NU s2_2;
{	result = (NU)0;
	s1_2 = s1_p1;
	s2_2 = s2_p2;
	{
		while (1) {
			NU64 x;
			if (!((NU64)(s2_2) <= (NU64)((NU)((NU64)(limit_p3) - (NU64)(((NU)8)))))) goto LA2;
			x = (NU64)((*((NU64*) ((&src_p0->data[s2_2])))) ^ (*((NU64*) ((&src_p0->data[(NU)((NU64)(s1_2) + (NU64)(result))])))));
			{
				NU matchingBits;
				NI T7_;
				if (!!((x == 0ULL))) goto LA5_;
				T7_ = (NI)0;
				T7_ = countTrailingZeroBits__librariesZsupersnappyZsupersnappy_u727(x);
				matchingBits = ((NU) (T7_));
				result += (NU)((NU64)(matchingBits) >> (NU64)(((NI)3)));
				goto BeforeRet_;
			}
LA5_: ;
			s2_2 += ((NI)8);
			result += ((NI)8);
		} LA2: ;
	}
	{
		while (1) {
			if (!((NU64)(s2_2) < (NU64)(limit_p3))) goto LA9;
			{
				if (!!(((NU8)(src_p0->data[s2_2]) == (NU8)(src_p0->data[(NU)((NU64)(s1_2) + (NU64)(result))])))) goto LA12_;
				goto BeforeRet_;
			}
LA12_: ;
			s2_2 += ((NI)1);
			result += ((NI)1);
		} LA9: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, emitCopy64Max__librariesZsupersnappyZsupersnappy_u798)(NimStringDesc** dst_p0, NU* op_p1, NU offset_p2, NU len_p3) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((NU64)(len_p3) < (NU64)(((NU)12)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NU64)(offset_p2) < (NU64)(((NU)2048)));
LA4_: ;
		if (!T3_) goto LA5_;
		(*dst_p0)->data[(*op_p1)] = ((NIM_CHAR) ((NU)((NU64)(((NU)1)) + (NU64)((NU)((NU64)((NU)((NU64)((NU)((NU64)(len_p3) - (NU64)(((NU)4)))) << (NU64)(((NI)2)))) + (NU64)((NU)((NU64)((NU)((NU64)(offset_p2) >> (NU64)(((NI)8)))) << (NU64)(((NI)5)))))))));
		(*op_p1) += ((NI)1);
		(*dst_p0)->data[(*op_p1)] = ((NIM_CHAR) ((NU)(offset_p2 & ((NU)255))));
		(*op_p1) += ((NI)1);
	}
	goto LA1_;
LA5_: ;
	{
		(*dst_p0)->data[(*op_p1)] = ((NIM_CHAR) ((NU)((NU64)(((NU)2)) + (NU64)((NU)((NU64)((NU)((NU64)(len_p3) - (NU64)(((NU)1)))) << (NU64)(((NI)2)))))));
		(*op_p1) += ((NI)1);
		(*((NU16*) ((&(*dst_p0)->data[(*op_p1)])))) = ((NU16) (offset_p2));
		(*op_p1) += ((NI)2);
	}
LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, emitCopy__librariesZsupersnappyZsupersnappy_u847)(NimStringDesc** dst_p0, NU* op_p1, NU offset_p2, NU len_p3) {
	NU len_2;
	len_2 = len_p3;
	{
		while (1) {
			if (!((NU64)(((NU)68)) <= (NU64)(len_2))) goto LA2;
			emitCopy64Max__librariesZsupersnappyZsupersnappy_u798(dst_p0, op_p1, offset_p2, ((NU)64));
			len_2 -= ((NI)64);
		} LA2: ;
	}
	{
		if (!((NU64)(((NU)64)) < (NU64)(len_2))) goto LA5_;
		emitCopy64Max__librariesZsupersnappyZsupersnappy_u798(dst_p0, op_p1, offset_p2, ((NU)60));
		len_2 -= ((NI)60);
	}
LA5_: ;
	emitCopy64Max__librariesZsupersnappyZsupersnappy_u798(dst_p0, op_p1, offset_p2, len_2);
}
N_LIB_PRIVATE N_NIMCALL(void, compressFragment__librariesZsupersnappyZsupersnappy_u861)(NimStringDesc** dst_p0, NimStringDesc* src_p1, NU* op_p2, NU start_p3, NU len_p4, tySequence__uFLLGQVsiasALrzzzvqnZw** compressTable_p5) {
	NU ipEnd;
	NU ip;
	NU nextEmit;
	NU tableSize;
	NU shift;
{	ipEnd = (NU)((NU64)(start_p3) + (NU64)(len_p4));
	ip = start_p3;
	nextEmit = ip;
	tableSize = ((NU)256);
	shift = ((NU)24);
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = ((NU64)(tableSize) < (NU64)(((NU)16384)));
			if (!(T3_)) goto LA4_;
			T3_ = ((NU64)(tableSize) < (NU64)(len_p4));
LA4_: ;
			if (!T3_) goto LA2;
			tableSize = (NU)((NU64)(tableSize) << (NU64)(((NI)1)));
			shift -= ((NI)1);
		} LA2: ;
	}
	zeroMem__system_u1756(((void*) ((&(*compressTable_p5)->data[((NI)0)]))), ((NI) ((NU)((NU64)(tableSize) * (NU64)(((NU)2))))));
	{
		NU ipLimit;
		NU32 nextHash;
		if (!((NU64)(((NU)15)) <= (NU64)(len_p4))) goto LA7_;
		ipLimit = (NU)((NU64)((NU)((NU64)(start_p3) + (NU64)(len_p4))) - (NU64)(((NU)15)));
		ip += ((NI)1);
		nextHash = (NU32)((NU32)((NU32)((NU32)((*((NU32*) ((&src_p1->data[ip]))))) * (NU32)(((NU32)506832829)))) >> (NU64)(shift));
		{
			while (1) {
				NU skipBytes;
				NU nextIp;
				NU candidate;
				NU64 inputBytes;
				NU32 candidateBytes;
				skipBytes = ((NU)32);
				nextIp = ip;
				candidate = (NU)0;
				{
					while (1) {
						NU32 h;
						NU bytesBetweenHashLookups;
						ip = nextIp;
						h = nextHash;
						bytesBetweenHashLookups = (NU)((NU64)(skipBytes) >> (NU64)(((NI)5)));
						skipBytes += ((NI)1);
						nextIp = (NU)((NU64)(ip) + (NU64)(bytesBetweenHashLookups));
						{
							if (!((NU64)(ipLimit) < (NU64)(nextIp))) goto LA15_;
							{
								if (!((NU64)(nextEmit) < (NU64)(ipEnd))) goto LA19_;
								emitLiteral__librariesZsupersnappyZsupersnappy_u498(dst_p0, src_p1, op_p2, nextEmit, (NU)((NU64)(ipEnd) - (NU64)(nextEmit)), NIM_FALSE);
							}
LA19_: ;
							goto BeforeRet_;
						}
LA15_: ;
						nextHash = (NU32)((NU32)((NU32)((NU32)((*((NU32*) ((&src_p1->data[nextIp]))))) * (NU32)(((NU32)506832829)))) >> (NU64)(shift));
						candidate = (NU)((NU64)(start_p3) + (NU64)(((NU) ((*compressTable_p5)->data[h]))));
						(*compressTable_p5)->data[h] = ((NU16) ((NU)((NU64)(ip) - (NU64)(start_p3))));
						{
							if (!((*((NU32*) ((&src_p1->data[ip])))) == (*((NU32*) ((&src_p1->data[candidate])))))) goto LA23_;
							goto LA11;
						}
LA23_: ;
					}
				} LA11: ;
				emitLiteral__librariesZsupersnappyZsupersnappy_u498(dst_p0, src_p1, op_p2, nextEmit, (NU)((NU64)(ip) - (NU64)(nextEmit)), NIM_TRUE);
				inputBytes = (NU64)0;
				candidateBytes = (NU32)0;
				{
					while (1) {
						NU matched;
						NU T27_;
						NU offset;
						NU insertTail;
						NU32 prevHash;
						NU32 curHash;
						T27_ = (NU)0;
						T27_ = findMatchLength__librariesZsupersnappyZsupersnappy_u648(src_p1, (NU)((NU64)(candidate) + (NU64)(((NU)4))), (NU)((NU64)(ip) + (NU64)(((NU)4))), ipEnd);
						matched = (NU)((NU64)(((NU)4)) + (NU64)(T27_));
						offset = (NU)((NU64)(ip) - (NU64)(candidate));
						ip += matched;
						emitCopy__librariesZsupersnappyZsupersnappy_u847(dst_p0, op_p2, offset, matched);
						insertTail = (NU)((NU64)(ip) - (NU64)(((NU)1)));
						nextEmit = ip;
						{
							if (!((NU64)(ipLimit) <= (NU64)(ip))) goto LA30_;
							{
								if (!((NU64)(nextEmit) < (NU64)(ipEnd))) goto LA34_;
								emitLiteral__librariesZsupersnappyZsupersnappy_u498(dst_p0, src_p1, op_p2, nextEmit, (NU)((NU64)(ipEnd) - (NU64)(nextEmit)), NIM_FALSE);
							}
LA34_: ;
							goto BeforeRet_;
						}
LA30_: ;
						inputBytes = (*((NU64*) ((&src_p1->data[insertTail]))));
						prevHash = (NU32)((NU32)((NU32)((NU32)(((NU32) ((NU64)((NU64)((NU64)(inputBytes) >> (NU64)(((NI)0))) & 4294967295ULL)))) * (NU32)(((NU32)506832829)))) >> (NU64)(shift));
						curHash = (NU32)((NU32)((NU32)((NU32)(((NU32) ((NU64)((NU64)((NU64)(inputBytes) >> (NU64)(((NI)8))) & 4294967295ULL)))) * (NU32)(((NU32)506832829)))) >> (NU64)(shift));
						(*compressTable_p5)->data[prevHash] = ((NU16) ((NU)((NU64)((NU)((NU64)(ip) - (NU64)(start_p3))) - (NU64)(((NU)1)))));
						candidate = (NU)((NU64)(start_p3) + (NU64)(((NU) ((*compressTable_p5)->data[curHash]))));
						candidateBytes = (*((NU32*) ((&src_p1->data[candidate]))));
						(*compressTable_p5)->data[curHash] = ((NU16) ((NU)((NU64)(ip) - (NU64)(start_p3))));
						{
							if (!!((((NU32) ((NU64)((NU64)((NU64)(inputBytes) >> (NU64)(((NI)8))) & 4294967295ULL))) == candidateBytes))) goto LA38_;
							goto LA25;
						}
LA38_: ;
					}
				} LA25: ;
				nextHash = (NU32)((NU32)((NU32)((NU32)(((NU32) ((NU64)((NU64)((NU64)(inputBytes) >> (NU64)(((NI)16))) & 4294967295ULL)))) * (NU32)(((NU32)506832829)))) >> (NU64)(shift));
				ip += ((NI)1);
			}
		}
	}
LA7_: ;
	{
		if (!((NU64)(nextEmit) < (NU64)(ipEnd))) goto LA42_;
		emitLiteral__librariesZsupersnappyZsupersnappy_u498(dst_p0, src_p1, op_p2, nextEmit, (NU)((NU64)(ipEnd) - (NU64)(nextEmit)), NIM_FALSE);
	}
LA42_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, compress__librariesZsupersnappyZsupersnappy_u1092)(NimStringDesc** dst_p0, NimStringDesc* src_p1) {
	NimStringDesc* varintBytes;
	NU ip;
	NU op;
	tySequence__uFLLGQVsiasALrzzzvqnZw* compressTable;
	{
		tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T5_;
		NimStringDesc* T6_;
		if (!(((NI)IL64(4294967295)) < (src_p1 ? src_p1->Sup.len : 0))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
		(*T5_).Sup.Sup.Sup.name = "SnappyError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.Sup.message; (*T5_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_3));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "SnappyError", "compress", "supersnappy.nim", 330);
	}
LA3_: ;
	unsureAsgnRef((void**) (&(*dst_p0)), setLengthStr((*dst_p0), ((NI) ((NI)((NI)(((NI)32) + (src_p1 ? src_p1->Sup.len : 0)) + (NI)((src_p1 ? src_p1->Sup.len : 0) / ((NI)6)))))));
	varintBytes = varint__librariesZsupersnappyZsupersnappyZcommon_u20(((NU32) ((src_p1 ? src_p1->Sup.len : 0))));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (varintBytes ? varintBytes->Sup.len : 0);
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA9;
				i = i_2;
				(*dst_p0)->data[i] = varintBytes->data[i];
				i_2 += ((NI)1);
			} LA9: ;
		}
	}
	ip = ((NU)0);
	op = ((NU) ((varintBytes ? varintBytes->Sup.len : 0)));
	compressTable = newSeq__librariesZsupersnappyZsupersnappy_u1112(((NI)16384));
	{
		while (1) {
			NU fragmentSize;
			NU bytesToRead;
			if (!((NU64)(ip) < (NU64)(((NU) ((src_p1 ? src_p1->Sup.len : 0)))))) goto LA11;
			fragmentSize = (NU)((NU64)(((NU) ((src_p1 ? src_p1->Sup.len : 0)))) - (NU64)(ip));
			bytesToRead = min__librariesZsupersnappyZsupersnappy_u1138(fragmentSize, ((NI)65536));
			{
				tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig* T16_;
				NimStringDesc* T17_;
				if (!((NU64)(bytesToRead) <= (NU64)(((NU)0)))) goto LA14_;
				T16_ = NIM_NIL;
				T16_ = (tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*) newObj((&NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_), sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig));
				(*T16_).Sup.Sup.Sup.Sup.m_type = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
				(*T16_).Sup.Sup.Sup.name = "SnappyError";
				T17_ = NIM_NIL;
				T17_ = (*T16_).Sup.Sup.Sup.message; (*T16_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__PlnUgi9cchxmhqZzbwsLzzA_3));
				if (T17_) nimGCunrefNoCycle(T17_);
				asgnRef((void**) (&(*T16_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
				raiseExceptionEx((Exception*)T16_, "SnappyError", "compress", "supersnappy.nim", 347);
			}
LA14_: ;
			compressFragment__librariesZsupersnappyZsupersnappy_u861(dst_p0, src_p1, (&op), ip, bytesToRead, (&compressTable));
			ip += bytesToRead;
		} LA11: ;
	}
	unsureAsgnRef((void**) (&(*dst_p0)), setLengthStr((*dst_p0), ((NI) (op))));
}
N_LIB_PRIVATE N_NIMCALL(void, atmlibrariesatssupersnappyatssupersnappydotnim_DatInit000)(void) {
static TNimNode TM__PlnUgi9cchxmhqZzbwsLzzA_0[1];
NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_.size = sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig);
NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_.align = NIM_ALIGNOF(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig);
NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_.kind = 17;
NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_.base = (&NTIvalueerror__I29b1dwcLrTw15fJ82YvM2g_);
TM__PlnUgi9cchxmhqZzbwsLzzA_0[0].len = 0; TM__PlnUgi9cchxmhqZzbwsLzzA_0[0].kind = 2;
NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_.node = &TM__PlnUgi9cchxmhqZzbwsLzzA_0[0];
NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_.size = sizeof(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*);
NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_.align = NIM_ALIGNOF(tyObject_SnappyError__7VbUCQF2JoJZQ1K15SbFig*);
NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_.kind = 22;
NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_.base = (&NTIsnappyerror__7VbUCQF2JoJZQ1K15SbFig_);
NTIrefsnappyerror__wWUu09bEDZScs6vMXWBt3uQ_.marker = Marker_tyRef__wWUu09bEDZScs6vMXWBt3uQ;
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.size = sizeof(tySequence__uFLLGQVsiasALrzzzvqnZw*);
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.align = NIM_ALIGNOF(tySequence__uFLLGQVsiasALrzzzvqnZw*);
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.kind = 24;
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.base = (&NTIuint4954__M4na42GvebBMnI5wV9cYMxg_);
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.flags = 2;
NTIseqLuint4954T__uFLLGQVsiasALrzzzvqnZw_.marker = Marker_tySequence__uFLLGQVsiasALrzzzvqnZw;
}

