# errors.py

error_list = [
    "ERROR 001\nINTERVAL CANNOT BE A FLOAT",
    "ERROR 002\nRAINBOW MUST BE A BOOL",
    "ERROR 003\nINTERVAL INCORRECT, CHOOSE BETWEEN 1-63 OR USE STATIC INSTEAD",
    "ERROR 004\nINVALID COLOR FORMAT",
    "ERROR 005\nRAINBOW AND STATIC CANNOT BOTH BE USED SIMULTANIOUSLY"
]