# Generated by Django 5.0.4 on 2024-06-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_herobiz_dental', '0003_portfolio_client_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
