import os

GCP_PROJECT_ID = os.getenv('PUBSUB_RPC_GCP_PROJECT_ID')
JOB_TOPIC_NAME = os.getenv('PUBSUB_RPC_JOB_TOPIC_NAME')
RESPONSE_TOPIC_NAME = os.getenv('PUBSUB_RPC_RESPONSE_TOPIC_NAME')
SERVER_INBOUND_SUBSCRIPTION_NAME = os.getenv(
    'PUBSUB_RPC_SERVER_INBOUND_SUBSCRIPTION_NAME')

MAX_TTL_CACHE_SIZE = int(os.getenv('PUBSUB_RPC_MAX_TTL_CACHE_SIZE', 9000))
JOB_CACHE_TTL = int(os.getenv('PUBSUB_RPC_JOB_CACHE_TTL', 300))


PUBLISH_BATCH_SIZE = int(os.getenv('PUBSUB_RPC_PUBLISH_BATCH_SIZE', 100))
PRODUCER_MAX_WAIT_TIME = int(os.getenv(
    'PUBSUB_RPC_PRODUCER_MAX_WAIT_TIME', 10))

ACK_BATCH_SIZE = int(os.getenv('PUBSUB_RPC_ACK_BATCH_SIZE', 100))
NACK_BATCH_SIZE = int(os.getenv('PUBSUB_RPC_NACK_BATCH_SIZE', 100))
ACK_MAX_WAIT_TIME = int(os.getenv('PUBSUB_RPC_ACK_MAX_WAIT_TIME', 5))
NACK_MAX_WAIT_TIME = int(os.getenv('PUBSUB_RPC_NACK_MAX_WAIT_TIME', 5))

CONSUMER_MAX_MESSAGE_REQUEST = int(os.getenv(
    'PUBSUB_RPC_CONSUMER_MAX_MESSAGE_REQUEST', 250))
CONSUMER_SLEEP_INTERVAL = int(os.getenv(
    'PUBSUB_RPC_CONSUMER_SLEEP_INTERVAL', 1))
