# coding: utf-8
"""
    Superwise Main Entities

    API reference

    The version of the OpenAPI document: 1.6.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import json
import pprint
import re  # noqa: F401

from aenum import Enum
from aenum import no_arg


class AlertOnStatusDirection(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    HEALTHY_TO_UNHEALTHY = "HEALTHY_TO_UNHEALTHY"
    UNHEALTHY_TO_HEALTHY = "UNHEALTHY_TO_HEALTHY"
    BOTH = "BOTH"

    @classmethod
    def from_json(cls, json_str: str) -> AlertOnStatusDirection:
        """Create an instance of AlertOnStatusDirection from a JSON string"""
        return AlertOnStatusDirection(json.loads(json_str))
