# coding: utf-8
"""
    Superwise Main Entities

    API reference

    The version of the OpenAPI document: 1.6.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel
from pydantic import constr
from pydantic import Field


class DashboardCreate(BaseModel):
    """
    DashboardCreate
    """

    name: constr(strict=True, max_length=100, min_length=1) = Field(...)
    __properties = ["name"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DashboardCreate:
        """Create an instance of DashboardCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DashboardCreate:
        """Create an instance of DashboardCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DashboardCreate.parse_obj(obj)

        _obj = DashboardCreate.parse_obj({"name": obj.get("name")})
        return _obj
