# coding: utf-8
"""
    Superwise Main Entities

    API reference

    The version of the OpenAPI document: 1.6.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import json
import pprint
import re  # noqa: F401

from aenum import Enum
from aenum import no_arg


class OpenAIModelVersion(str, Enum):
    """
    OpenAIModelVersion
    """

    """
    allowed enum values
    """
    GPT_MINUS_3_DOT_5_MINUS_TURBO = "gpt-3.5-turbo"
    GPT_MINUS_3_DOT_5_MINUS_TURBO_MINUS_1106 = "gpt-3.5-turbo-1106"
    GPT_MINUS_3_DOT_5_MINUS_TURBO_MINUS_16K = "gpt-3.5-turbo-16k"
    GPT_MINUS_4 = "gpt-4"
    GPT_MINUS_4_MINUS_VISION_MINUS_PREVIEW = "gpt-4-vision-preview"
    GPT_MINUS_4_MINUS_1106_MINUS_PREVIEW = "gpt-4-1106-preview"

    @classmethod
    def from_json(cls, json_str: str) -> OpenAIModelVersion:
        """Create an instance of OpenAIModelVersion from a JSON string"""
        return OpenAIModelVersion(json.loads(json_str))
