# coding: utf-8
"""
    Superwise Main Entities

    API reference

    The version of the OpenAPI document: 1.6.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import json
import pprint
import re  # noqa: F401

from aenum import Enum
from aenum import no_arg


class PolicyStatus(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    PENDING = "pending"
    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    INACTIVE = "inactive"

    @classmethod
    def from_json(cls, json_str: str) -> PolicyStatus:
        """Create an instance of PolicyStatus from a JSON string"""
        return PolicyStatus(json.loads(json_str))
