"""
NOTE: Code in this package will be deployed in the scoring server of the RAG Studio app.
It is imperative that we keep the dependencies and imports of this package to a minimum
in order to reduce the size of the model image being served by the endpoint.

Functionality for unpacking payloads generated by RAG endpoints.
"""

from databricks.rag.unpacking.unpack import unpack_and_split_payloads

__all__ = ["unpack_and_split_payloads"]
