# Generated by Django 5.0.6 on 2024-06-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postds', '0004_rename_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default', max_length=40, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sns',
            field=models.URLField(blank=True, help_text='공란 가능', max_length=500, null=True, verbose_name='sns'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to='django_postds.profile'),
        ),
    ]
