from ..__const import Const


class CapabilitiesConst(Const):
    PLATFORM_NAME = "PLATFORM_NAME"
    PLATFORM_VERSION = "PLATFORM_VERSION"
    DEVICE_NAME = "DEVICE_NAME"
    APP_PACKAGE = "APP_PACKAGE"
    APP_ACTIVITIES = "APP_ACTIVITIES"
    BUNDLE_IDENTIFIER = "BUNDLE_IDENTIFIER"
    DEVICE_ID = "DEVICE_ID"
    APP_VERSION = "APP_VERSION"
    DEVICE_CODE = "DEVICE_CODE"
