
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-12T15:04:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebdaaf1da0b280f6691cf8122dcbd6b9b586eb0a",
 "version": "0.2.4a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
