
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-09T20:38:15+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "64dc14d4fe96a00791a143c3b258e4f5b6f1c630",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
