# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vsdx-rdf',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/vsdx-rdf',
                'lib_path': 'vsdx_rdf'},
  'syms': { 'vsdx_rdf.core': { 'vsdx_rdf.core.Client': ('core.html#client', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.__init__': ('core.html#client.__init__', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.convert': ('core.html#client.convert', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.convertToRdf': ('core.html#client.converttordf', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.createNodesAndEdges': ('core.html#client.createnodesandedges', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.main': ('core.html#client.main', 'vsdx_rdf/core.py'),
                               'vsdx_rdf.core.Client.save': ('core.html#client.save', 'vsdx_rdf/core.py')},
            'vsdx_rdf.visualize': { 'vsdx_rdf.visualize.VisualizeClient': ('visualize.html#visualizeclient', 'vsdx_rdf/visualize.py'),
                                    'vsdx_rdf.visualize.VisualizeClient.graph_draw_by_kanzaki': ( 'visualize.html#visualizeclient.graph_draw_by_kanzaki',
                                                                                                  'vsdx_rdf/visualize.py')}}}
