# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\xb0\xc5\xe1.'
full_git_hash = 'b0c5e12e2671484109c86d1ea6de34b4feee8d40'
git_branch = 'HEAD'
dirty = False
