
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-13T16:54:19+1200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c86beb9020f0950ec13323eb3e5c7164d8e05635",
 "version": "1.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
