# Generated by Django 2.2.23 on 2021-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_popup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="popuppluginmodel",
            name="popup_template",
            field=models.CharField(
                choices=[("bottom_right.html", "Bottom right popup")],
                default="Bottom right popup",
                max_length=300,
                verbose_name="Popup style",
            ),
            preserve_default=False,
        )
    ]
