
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-10T18:07:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1809a0aea245442d5a9d0779de5bfcd683dc3eb1",
 "version": "0.28.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
