# coding: utf-8

"""
    Workspace Data Service

    This page lists current APIs. As of v0.2, all APIs are subject to change without notice.   # noqa: E501

    The version of the OpenAPI document: v0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wds_client
from wds_client.api.import_api import ImportApi  # noqa: E501
from wds_client.rest import ApiException


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self):
        self.api = wds_client.api.import_api.ImportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_import_v1(self):
        """Test case for import_v1

        Import from a file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
