'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.21

version: 0.1.21

full_version: 0.1.21

git_revision: 218bc0ef9108ae440c58cdc3da620ea4b8d5631d

release: True

'''
short_version: str = '0.1.21'
version: str = '0.1.21'
full_version: str = '0.1.21'
git_revision: str = '218bc0ef9108ae440c58cdc3da620ea4b8d5631d'
release: bool = True
if not release:
    version = full_version
