# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/UserInterface/UserInterfaceServices.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openobd_protocol.UserInterface import UserInterface_pb2 as openobd__protocol_dot_UserInterface_dot_UserInterface__pb2
from openobd_protocol import Status_pb2 as openobd__protocol_dot_Status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:openobd_protocol/UserInterface/UserInterfaceServices.proto\x12+com.jifeline.OpenOBD.Protocol.UserInterface\x1a\x32openobd_protocol/UserInterface/UserInterface.proto\x1a\x1dopenobd_protocol/Status.proto2\xa1\x01\n\x15UserInterfaceServices\x12\x87\x01\n\x07\x63ontrol\x12:.com.jifeline.OpenOBD.Protocol.UserInterface.UserInterface\x1a:.com.jifeline.OpenOBD.Protocol.UserInterface.UserInterface\"\x00(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.UserInterface.UserInterfaceServices_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_USERINTERFACESERVICES']._serialized_start=191
  _globals['_USERINTERFACESERVICES']._serialized_end=352
# @@protoc_insertion_point(module_scope)
