# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_corporations_corporation_id_contacts_labels200_ok import GetCorporationsCorporationIdContactsLabels200Ok  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetCorporationsCorporationIdContactsLabels200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdContactsLabels200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCorporationsCorporationIdContactsLabels200Ok(self):
        """Test GetCorporationsCorporationIdContactsLabels200Ok"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_corporations_corporation_id_contacts_labels200_ok.GetCorporationsCorporationIdContactsLabels200Ok()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
