# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_fw_leaderboards_characters_active_total_active_total import GetFwLeaderboardsCharactersActiveTotalActiveTotal  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetFwLeaderboardsCharactersActiveTotalActiveTotal(unittest.TestCase):
    """GetFwLeaderboardsCharactersActiveTotalActiveTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFwLeaderboardsCharactersActiveTotalActiveTotal(self):
        """Test GetFwLeaderboardsCharactersActiveTotalActiveTotal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_fw_leaderboards_characters_active_total_active_total.GetFwLeaderboardsCharactersActiveTotalActiveTotal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
