# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.post_corporations_corporation_id_assets_locations_position import PostCorporationsCorporationIdAssetsLocationsPosition  # noqa: E501
from eve_netease_api.rest import ApiException


class TestPostCorporationsCorporationIdAssetsLocationsPosition(unittest.TestCase):
    """PostCorporationsCorporationIdAssetsLocationsPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostCorporationsCorporationIdAssetsLocationsPosition(self):
        """Test PostCorporationsCorporationIdAssetsLocationsPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.post_corporations_corporation_id_assets_locations_position.PostCorporationsCorporationIdAssetsLocationsPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
