# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.api.assets_api import AssetsApi  # noqa: E501
from eve_netease_api.rest import ApiException


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self):
        self.api = eve_netease_api.api.assets_api.AssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_characters_character_id_assets(self):
        """Test case for get_characters_character_id_assets

        Get character assets  # noqa: E501
        """
        pass

    def test_get_corporations_corporation_id_assets(self):
        """Test case for get_corporations_corporation_id_assets

        Get corporation assets  # noqa: E501
        """
        pass

    def test_post_characters_character_id_assets_locations(self):
        """Test case for post_characters_character_id_assets_locations

        Get character asset locations  # noqa: E501
        """
        pass

    def test_post_characters_character_id_assets_names(self):
        """Test case for post_characters_character_id_assets_names

        Get character asset names  # noqa: E501
        """
        pass

    def test_post_corporations_corporation_id_assets_locations(self):
        """Test case for post_corporations_corporation_id_assets_locations

        Get corporation asset locations  # noqa: E501
        """
        pass

    def test_post_corporations_corporation_id_assets_names(self):
        """Test case for post_corporations_corporation_id_assets_names

        Get corporation asset names  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
