# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_dogma_effects_effect_id_ok import GetDogmaEffectsEffectIdOk  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetDogmaEffectsEffectIdOk(unittest.TestCase):
    """GetDogmaEffectsEffectIdOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDogmaEffectsEffectIdOk(self):
        """Test GetDogmaEffectsEffectIdOk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_dogma_effects_effect_id_ok.GetDogmaEffectsEffectIdOk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
