# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.api.opportunities_api import OpportunitiesApi  # noqa: E501
from eve_netease_api.rest import ApiException


class TestOpportunitiesApi(unittest.TestCase):
    """OpportunitiesApi unit test stubs"""

    def setUp(self):
        self.api = eve_netease_api.api.opportunities_api.OpportunitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_characters_character_id_opportunities(self):
        """Test case for get_characters_character_id_opportunities

        Get a character's completed tasks  # noqa: E501
        """
        pass

    def test_get_opportunities_groups(self):
        """Test case for get_opportunities_groups

        Get opportunities groups  # noqa: E501
        """
        pass

    def test_get_opportunities_groups_group_id(self):
        """Test case for get_opportunities_groups_group_id

        Get opportunities group  # noqa: E501
        """
        pass

    def test_get_opportunities_tasks(self):
        """Test case for get_opportunities_tasks

        Get opportunities tasks  # noqa: E501
        """
        pass

    def test_get_opportunities_tasks_task_id(self):
        """Test case for get_opportunities_tasks_task_id

        Get opportunities task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
