# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_universe_schematics_schematic_id_not_found import GetUniverseSchematicsSchematicIdNotFound  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetUniverseSchematicsSchematicIdNotFound(unittest.TestCase):
    """GetUniverseSchematicsSchematicIdNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUniverseSchematicsSchematicIdNotFound(self):
        """Test GetUniverseSchematicsSchematicIdNotFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_universe_schematics_schematic_id_not_found.GetUniverseSchematicsSchematicIdNotFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
