# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_universe_system_jumps200_ok import GetUniverseSystemJumps200Ok  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetUniverseSystemJumps200Ok(unittest.TestCase):
    """GetUniverseSystemJumps200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUniverseSystemJumps200Ok(self):
        """Test GetUniverseSystemJumps200Ok"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_universe_system_jumps200_ok.GetUniverseSystemJumps200Ok()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
