# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_netease_api
from eve_netease_api.models.get_fw_leaderboards_characters_yesterday_yesterday1 import GetFwLeaderboardsCharactersYesterdayYesterday1  # noqa: E501
from eve_netease_api.rest import ApiException


class TestGetFwLeaderboardsCharactersYesterdayYesterday1(unittest.TestCase):
    """GetFwLeaderboardsCharactersYesterdayYesterday1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFwLeaderboardsCharactersYesterdayYesterday1(self):
        """Test GetFwLeaderboardsCharactersYesterdayYesterday1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_netease_api.models.get_fw_leaderboards_characters_yesterday_yesterday1.GetFwLeaderboardsCharactersYesterdayYesterday1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
