
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-13T12:06:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bf759c3ef9cefe7d3bf36d85951778d96120e63",
 "version": "1.26.0.post0.dev33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
