# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pyBiDirectionalCpp
else:
    import _pyBiDirectionalCpp

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyBiDirectionalCpp.delete_SwigPyIterator

    def value(self):
        return _pyBiDirectionalCpp.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyBiDirectionalCpp.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyBiDirectionalCpp.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyBiDirectionalCpp.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyBiDirectionalCpp.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyBiDirectionalCpp.SwigPyIterator_copy(self)

    def next(self):
        return _pyBiDirectionalCpp.SwigPyIterator_next(self)

    def __next__(self):
        return _pyBiDirectionalCpp.SwigPyIterator___next__(self)

    def previous(self):
        return _pyBiDirectionalCpp.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyBiDirectionalCpp.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyBiDirectionalCpp.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyBiDirectionalCpp.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyBiDirectionalCpp.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyBiDirectionalCpp.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyBiDirectionalCpp.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyBiDirectionalCpp.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _pyBiDirectionalCpp:
_pyBiDirectionalCpp.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyBiDirectionalCpp.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyBiDirectionalCpp.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _pyBiDirectionalCpp.DoubleVector___bool__(self)

    def __len__(self):
        return _pyBiDirectionalCpp.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _pyBiDirectionalCpp.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyBiDirectionalCpp.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyBiDirectionalCpp.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyBiDirectionalCpp.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyBiDirectionalCpp.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyBiDirectionalCpp.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _pyBiDirectionalCpp.DoubleVector_pop(self)

    def append(self, x):
        return _pyBiDirectionalCpp.DoubleVector_append(self, x)

    def empty(self):
        return _pyBiDirectionalCpp.DoubleVector_empty(self)

    def size(self):
        return _pyBiDirectionalCpp.DoubleVector_size(self)

    def swap(self, v):
        return _pyBiDirectionalCpp.DoubleVector_swap(self, v)

    def begin(self):
        return _pyBiDirectionalCpp.DoubleVector_begin(self)

    def end(self):
        return _pyBiDirectionalCpp.DoubleVector_end(self)

    def rbegin(self):
        return _pyBiDirectionalCpp.DoubleVector_rbegin(self)

    def rend(self):
        return _pyBiDirectionalCpp.DoubleVector_rend(self)

    def clear(self):
        return _pyBiDirectionalCpp.DoubleVector_clear(self)

    def get_allocator(self):
        return _pyBiDirectionalCpp.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _pyBiDirectionalCpp.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _pyBiDirectionalCpp.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _pyBiDirectionalCpp.DoubleVector_swiginit(self, _pyBiDirectionalCpp.new_DoubleVector(*args))

    def push_back(self, x):
        return _pyBiDirectionalCpp.DoubleVector_push_back(self, x)

    def front(self):
        return _pyBiDirectionalCpp.DoubleVector_front(self)

    def back(self):
        return _pyBiDirectionalCpp.DoubleVector_back(self)

    def assign(self, n, x):
        return _pyBiDirectionalCpp.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _pyBiDirectionalCpp.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _pyBiDirectionalCpp.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _pyBiDirectionalCpp.DoubleVector_reserve(self, n)

    def capacity(self):
        return _pyBiDirectionalCpp.DoubleVector_capacity(self)
    __swig_destroy__ = _pyBiDirectionalCpp.delete_DoubleVector

# Register DoubleVector in _pyBiDirectionalCpp:
_pyBiDirectionalCpp.DoubleVector_swigregister(DoubleVector)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _pyBiDirectionalCpp.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pyBiDirectionalCpp.IntVector___nonzero__(self)

    def __bool__(self):
        return _pyBiDirectionalCpp.IntVector___bool__(self)

    def __len__(self):
        return _pyBiDirectionalCpp.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pyBiDirectionalCpp.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pyBiDirectionalCpp.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pyBiDirectionalCpp.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pyBiDirectionalCpp.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pyBiDirectionalCpp.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pyBiDirectionalCpp.IntVector___setitem__(self, *args)

    def pop(self):
        return _pyBiDirectionalCpp.IntVector_pop(self)

    def append(self, x):
        return _pyBiDirectionalCpp.IntVector_append(self, x)

    def empty(self):
        return _pyBiDirectionalCpp.IntVector_empty(self)

    def size(self):
        return _pyBiDirectionalCpp.IntVector_size(self)

    def swap(self, v):
        return _pyBiDirectionalCpp.IntVector_swap(self, v)

    def begin(self):
        return _pyBiDirectionalCpp.IntVector_begin(self)

    def end(self):
        return _pyBiDirectionalCpp.IntVector_end(self)

    def rbegin(self):
        return _pyBiDirectionalCpp.IntVector_rbegin(self)

    def rend(self):
        return _pyBiDirectionalCpp.IntVector_rend(self)

    def clear(self):
        return _pyBiDirectionalCpp.IntVector_clear(self)

    def get_allocator(self):
        return _pyBiDirectionalCpp.IntVector_get_allocator(self)

    def pop_back(self):
        return _pyBiDirectionalCpp.IntVector_pop_back(self)

    def erase(self, *args):
        return _pyBiDirectionalCpp.IntVector_erase(self, *args)

    def __init__(self, *args):
        _pyBiDirectionalCpp.IntVector_swiginit(self, _pyBiDirectionalCpp.new_IntVector(*args))

    def push_back(self, x):
        return _pyBiDirectionalCpp.IntVector_push_back(self, x)

    def front(self):
        return _pyBiDirectionalCpp.IntVector_front(self)

    def back(self):
        return _pyBiDirectionalCpp.IntVector_back(self)

    def assign(self, n, x):
        return _pyBiDirectionalCpp.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pyBiDirectionalCpp.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pyBiDirectionalCpp.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pyBiDirectionalCpp.IntVector_reserve(self, n)

    def capacity(self):
        return _pyBiDirectionalCpp.IntVector_capacity(self)
    __swig_destroy__ = _pyBiDirectionalCpp.delete_IntVector

# Register IntVector in _pyBiDirectionalCpp:
_pyBiDirectionalCpp.IntVector_swigregister(IntVector)
class BiDirectionalCpp(object):
    r"""
    BiDirectional algorithm. see docs

    1. ctor (memory allocation for the graph)
    2. add edges to graph using `addEdge`.
    3. [optional] set solving parameters if desired (e.g. time_limit, ...)
    	3.1. [optional] set callback using `setREFCallback`
    	3.2. [optional] set seed using `setSeed`
    4. call `run`
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, number_vertices, number_edges, source_id, sink_id, max_res_in, min_res_in):
        r"""
        :type number_vertices: int, in
        :param number_vertices:, int number of vertices in the graph (to be
            added using addEdge)
        :type number_edges: int, in
        :param number_edges:, int number of edges in the graph
        :type source_id: int, in
        :param source_id:, int vertex id for the source
        :type sink_id: int, in
        :param sink_id:, int vertex id for the sink
        :param max_res:, vector of double with upper bound for resource
            consumption
        :param min_res:, vector of double with lower bound for resource
            consumption
        """
        _pyBiDirectionalCpp.BiDirectionalCpp_swiginit(self, _pyBiDirectionalCpp.new_BiDirectionalCpp(number_vertices, number_edges, source_id, sink_id, max_res_in, min_res_in))
    __swig_destroy__ = _pyBiDirectionalCpp.delete_BiDirectionalCpp
    max_res = property(_pyBiDirectionalCpp.BiDirectionalCpp_max_res_get, _pyBiDirectionalCpp.BiDirectionalCpp_max_res_set, doc=r""" vector with upper and lower bounds for resources""")
    min_res = property(_pyBiDirectionalCpp.BiDirectionalCpp_min_res_get, _pyBiDirectionalCpp.BiDirectionalCpp_min_res_set)
    source_id = property(_pyBiDirectionalCpp.BiDirectionalCpp_source_id_get, _pyBiDirectionalCpp.BiDirectionalCpp_source_id_set)
    sink_id = property(_pyBiDirectionalCpp.BiDirectionalCpp_sink_id_get, _pyBiDirectionalCpp.BiDirectionalCpp_sink_id_set)

    def addNodes(self, nodes):
        r""" Wrapper to add nodes to the graph. See also: DiGraph::addNodes"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_addNodes(self, nodes)

    def addEdge(self, tail, head, weight, resource_consumption):
        r""" Add an edge to the graph"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_addEdge(self, tail, head, weight, resource_consumption)

    def run(self):
        r""" run the algorithm (assumes all the appropriate options are set)"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_run(self)

    def getPath(self):
        r""" Return the final path"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_getPath(self)

    def getConsumedResources(self):
        r""" Return the consumed resources"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_getConsumedResources(self)

    def getTotalCost(self):
        r""" Return the total cost"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_getTotalCost(self)

    def checkCriticalRes(self):
        r"""
        After running the algorithm, one can check if critical resource is tight
        (difference between final resource and maximum) and prints a message if it
        doesn't match to the one chosen in Params.
        """
        return _pyBiDirectionalCpp.BiDirectionalCpp_checkCriticalRes(self)

    def setDirection(self, direction_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setDirection(self, direction_in)

    def setMethod(self, method_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setMethod(self, method_in)

    def setTimeLimit(self, time_limit_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setTimeLimit(self, time_limit_in)

    def setThreshold(self, threshold_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setThreshold(self, threshold_in)

    def setElementary(self, elementary_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setElementary(self, elementary_in)

    def setTwoCycleElimination(self, two_cycle_elimination_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setTwoCycleElimination(self, two_cycle_elimination_in)

    def setBoundsPruning(self, bounds_pruning_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setBoundsPruning(self, bounds_pruning_in)

    def setFindCriticalRes(self, find_critical_res_in):
        r""" See also: bidirectional::Params and getCriticalRes"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setFindCriticalRes(self, find_critical_res_in)

    def setCriticalRes(self, critical_res_in):
        r""" See also: bidirectional::Params"""
        return _pyBiDirectionalCpp.BiDirectionalCpp_setCriticalRes(self, critical_res_in)

    def setREFCallback(self, cb):
        r"""
        Pass python callback for label extensions.
        Note: swig needs namespace specifier
        """
        return _pyBiDirectionalCpp.BiDirectionalCpp_setREFCallback(self, cb)

# Register BiDirectionalCpp in _pyBiDirectionalCpp:
_pyBiDirectionalCpp.BiDirectionalCpp_swigregister(BiDirectionalCpp)
class REFCallback(object):
    r"""
    Generic callback for custom Resource Extensions.
    In the case the user has not defined all three, default additive REFs are
    used.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == REFCallback:
            _self = None
        else:
            _self = self
        _pyBiDirectionalCpp.REFCallback_swiginit(self, _pyBiDirectionalCpp.new_REFCallback(_self, ))
    __swig_destroy__ = _pyBiDirectionalCpp.delete_REFCallback

    def REF_fwd(self, cumulative_resource, tail, head, edge_resource_consumption, partial_path, accummulated_cost):
        r""" Default implementation of a forward REF"""
        return _pyBiDirectionalCpp.REFCallback_REF_fwd(self, cumulative_resource, tail, head, edge_resource_consumption, partial_path, accummulated_cost)

    def REF_bwd(self, cumulative_resource, tail, head, edge_resource_consumption, partial_path, accummulated_cost):
        r"""
        Default implementation of a backward REF (note that critical resource
        information is not an argument)
        """
        return _pyBiDirectionalCpp.REFCallback_REF_bwd(self, cumulative_resource, tail, head, edge_resource_consumption, partial_path, accummulated_cost)

    def REF_join(self, fwd_resource, bwd_resource, tail, head, edge_resource_consumption):
        r"""
        Default implementation of a joining REF (used to merge forward and
        backward paths)
        """
        return _pyBiDirectionalCpp.REFCallback_REF_join(self, fwd_resource, bwd_resource, tail, head, edge_resource_consumption)
    def __disown__(self):
        self.this.disown()
        _pyBiDirectionalCpp.disown_REFCallback(self)
        return weakref.proxy(self)

# Register REFCallback in _pyBiDirectionalCpp:
_pyBiDirectionalCpp.REFCallback_swigregister(REFCallback)

def additiveForwardREF(cumulative_resource, edge_resource_consumption):
    r""" Default additive REF for forward labels"""
    return _pyBiDirectionalCpp.additiveForwardREF(cumulative_resource, edge_resource_consumption)

def additiveBackwardREF(cumulative_resource, edge_resource_consumption, critical_res=0):
    r""" Default additive REF for backward labels"""
    return _pyBiDirectionalCpp.additiveBackwardREF(cumulative_resource, edge_resource_consumption, critical_res)

