{
    "matches": [
        {
            "matchId": "1742474559872835584",
            "createTime": 1704273283,
            "endTime": 1704273723,
            "teammates": {
                "players": [
                    {
                        "accountId": "4300009616",
                        "nickname": "backend@awsl",
                        "preTeamId": 1,
                        "rank": 2,
                        "battlePoints": 1042,
                        "kills": 1,
                        "damage": 1444,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "10013908",
                        "nickname": "后台木木木",
                        "preTeamId": 1,
                        "rank": 2,
                        "battlePoints": 1000,
                        "kills": 2,
                        "damage": 779,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300016853",
                        "nickname": "后台jy",
                        "preTeamId": 1,
                        "rank": 2,
                        "battlePoints": 1180,
                        "kills": 2,
                        "damage": 536,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300016997",
                        "nickname": "zyl-1",
                        "preTeamId": 1,
                        "rank": 2,
                        "battlePoints": 1130,
                        "kills": 2,
                        "damage": 2132,
                        "rankingPoints": 0,
                    },
                ],
                "wAvgRank": 0,
                "wAvgRankingPoints": 0,
                "wAvgBattlePoints": 0,
            },
            "opponents": {
                "players": [
                    {
                        "accountId": "4300001471",
                        "nickname": "FFD@孙大聪明粉丝团",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 4,
                        "damage": 1970,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "10006776",
                        "nickname": "qiqi！",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 5,
                        "damage": 1728,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300014326",
                        "nickname": "FFD@酷酷长大中",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 1,
                        "damage": 1353,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "10007943",
                        "nickname": "bigfoot",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1000,
                        "kills": 6,
                        "damage": 2586,
                        "rankingPoints": 0,
                    },
                ],
                "wAvgRank": 0,
                "wAvgRankingPoints": 0,
                "wAvgBattlePoints": 0,
            },
            "result": {
                "finalScore": [1, 4],
                "rankingPointsBefore": 1,
                "rankingPointsAfter": 1,
                "battlePointsBefore": 1042,
                "battlePointsAfter": 1002,
            },
        },
        {
            "matchId": "1739938135088842752",
            "createTime": 1703668553,
            "endTime": 1703668965,
            "teammates": {
                "players": [
                    {
                        "accountId": "4300009616",
                        "nickname": "backend@awsl",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1000,
                        "kills": 2,
                        "damage": 1431,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300012663",
                        "nickname": "UIFX_嘎嘎乱杀",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 4,
                        "damage": 1986,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300016853",
                        "nickname": "后台jy",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 6,
                        "damage": 2811,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300017375",
                        "nickname": "Walker1",
                        "preTeamId": 1,
                        "rank": 1,
                        "battlePoints": 1130,
                        "kills": 4,
                        "damage": 1167,
                        "rankingPoints": 0,
                    },
                ],
                "wAvgRank": 0,
                "wAvgRankingPoints": 0,
                "wAvgBattlePoints": 0,
            },
            "opponents": {
                "players": [
                    {
                        "accountId": "4300015140",
                        "nickname": "art-机长3号",
                        "preTeamId": 1,
                        "battlePoints": 1130,
                        "kills": 1,
                        "damage": 1133,
                        "rank": 0,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "10014171",
                        "nickname": "Art-角色-你干嘛",
                        "preTeamId": 1,
                        "battlePoints": 1130,
                        "kills": 2,
                        "damage": 1926,
                        "rank": 0,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300003890",
                        "nickname": "Art_角色_凯瑟琳",
                        "preTeamId": 1,
                        "battlePoints": 1130,
                        "kills": 3,
                        "damage": 1891,
                        "rank": 0,
                        "rankingPoints": 0,
                    },
                    {
                        "accountId": "4300012642",
                        "nickname": "YYYS",
                        "preTeamId": 1,
                        "battlePoints": 1130,
                        "damage": 423,
                        "rank": 0,
                        "rankingPoints": 0,
                        "kills": 0,
                    },
                ],
                "wAvgRank": 0,
                "wAvgRankingPoints": 0,
                "wAvgBattlePoints": 0,
            },
            "result": {
                "finalScore": [4, 1],
                "rankingPointsAfter": 1,
                "battlePointsBefore": 1000,
                "battlePointsAfter": 1042,
                "rankingPointsBefore": 0,
            },
        },
    ]
}
